/**
 * Comprehensive TaxBD Statutory Rules & Historical Comparison Dataset
 * Fully referenced against official Bangladesh Income Tax Act 2023, Finance Acts, and NBR Paripatras.
 */

export const RULES_BY_YEAR = {
  '2024-2025': {
    assessmentYear: '2024-2025',
    incomeYear: '2023-2024',
    status: 'Current Applicable Law (Official)',
    statusBn: 'চলতি কার্যকর আইন (অফিশিয়াল)',
    act: 'Income Tax Act 2023 (Act No. 18 of 2023) & Finance Act 2024',
    actBn: 'আয়কর আইন ২০২৩ (২০২৩ সনের ১৮ নং আইন) ও অর্থ আইন ২০২৪',
    gazetteRef: 'Bangladesh Gazette Extra Ordinary, 30 June 2024',
    gazetteRefBn: 'বাংলাদেশ গেজেট অতিরিক্ত, ৩০ জুন ২০২৪',
    lastVerified: 'September 2024',
    generalThreshold: 350000,
    exemptionThresholds: [
      {
        id: 'general',
        category: 'General Individual (Male)',
        categoryBn: 'সাধারণ ব্যক্তি করদাতা (পুরুষ)',
        limit: 350000,
        formatted: '৳ 3,50,000',
        formattedBn: '৳ ৩,৫০,০০০',
        description: 'Under 65 years without special statutory status',
        descriptionBn: 'বিশেষ সুবিধা বহির্ভূত ৬৫ বছরের কম বয়সী করদাতা'
      },
      {
        id: 'female',
        category: 'Female Taxpayers',
        categoryBn: 'মহিলা করদাতা',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'All female individual taxpayers',
        descriptionBn: 'সকল নারী ব্যক্তি করদাতার জন্য প্রযোজ্য'
      },
      {
        id: 'seniorCitizen',
        category: 'Senior Citizens (Age 65+)',
        categoryBn: 'প্রবীণ নাগরিক (বয়স ৬৫ বা তদূর্ধ্ব)',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'Taxpayers aged 65 years or older as of income year',
        descriptionBn: 'আয়বর্ষে ৬৫ বছর বা তার বেশি বয়সী করদাতা'
      },
      {
        id: 'thirdGender',
        category: 'Third Gender Taxpayers',
        categoryBn: 'তৃতীয় লিঙ্গের করদাতা',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'Taxpayers of the third gender community',
        descriptionBn: 'তৃতীয় লিঙ্গ (হিজড়া) সম্প্রদায়ের করদাতা'
      },
      {
        id: 'disabled',
        category: 'Persons with Disabilities',
        categoryBn: 'প্রতিবন্ধী ব্যক্তি করদাতা',
        limit: 475000,
        formatted: '৳ 4,75,000',
        formattedBn: '৳ ৪,৭৫,০০০',
        description: 'Certified physically/mentally challenged individuals',
        descriptionBn: 'সনদপ্রাপ্ত শারীরিক বা মানসিক প্রতিবন্ধী করদাতা'
      },
      {
        id: 'freedomFighter',
        category: 'Gazetted Freedom Fighters',
        categoryBn: 'গেজেটভুক্ত যুদ্ধাহত বীর মুক্তিযোদ্ধা',
        limit: 500000,
        formatted: '৳ 5,00,000',
        formattedBn: '৳ ৫,০০,০০০',
        description: 'Gazetted war-wounded freedom fighters of Bangladesh',
        descriptionBn: 'বাংলাদেশ গেজেটভুক্ত খেতাবপ্রাপ্ত/যুদ্ধাহত বীর মুক্তিযোদ্ধা'
      },
      {
        id: 'parentOfDisabled',
        category: 'Parent/Guardian of Disabled Child',
        categoryBn: 'প্রতিবন্ধী সন্তানের পিতা/মাতা বা অভিভাবক',
        limit: 50000,
        formatted: '+ ৳ 50,000 / child',
        formattedBn: '+ ৳ ৫০,০০০ / সন্তান',
        description: 'Additional tax-free limit per disabled dependent child',
        descriptionBn: 'প্রতিটি প্রতিবন্ধী সন্তানের জন্য অতিরিক্ত করমুক্ত সীমা'
      },
    ],
    slabs: [
      { sequence: 1, range: 'First ৳ 3,50,000*', rangeBn: 'প্রথম ৩,৫০,০০০ টাকা পর্যন্ত*', lowerLimit: 0, upperLimit: 350000, rate: 0, description: 'Tax-free exemption limit (based on category)', descriptionBn: 'করমুক্ত আয়ের প্রারম্ভিক সীমা (শ্রেণি অনুযায়ী)' },
      { sequence: 2, range: 'Next ৳ 1,00,000', rangeBn: 'পরবর্তী ১,০০,০০০ টাকা পর্যন্ত', lowerLimit: 350000, upperLimit: 450000, rate: 5, description: 'Lowest progressive taxable tier', descriptionBn: 'সর্বনিম্ন প্রগতিশীল করযোগ্য ধাপ' },
      { sequence: 3, range: 'Next ৳ 4,00,000', rangeBn: 'পরবর্তী ৪,০০,০০০ টাকা পর্যন্ত', lowerLimit: 450000, upperLimit: 850000, rate: 10, description: 'Middle bracket (expanded from ৳3L)', descriptionBn: 'মধ্যবর্তী কর ধাপ (পূর্বের ৩ লাখ থেকে বর্ধিত)' },
      { sequence: 4, range: 'Next ৳ 5,00,000', rangeBn: 'পরবর্তী ৫,০০,০০০ টাকা পর্যন্ত', lowerLimit: 850000, upperLimit: 1350000, rate: 15, description: 'Upper-middle bracket (expanded from ৳4L)', descriptionBn: 'উচ্চ-মধ্যবর্তী কর ধাপ (পূর্বের ৪ লাখ থেকে বর্ধিত)' },
      { sequence: 5, range: 'Next ৳ 5,00,000', rangeBn: 'পরবর্তী ৫,০০,০০০ টাকা পর্যন্ত', lowerLimit: 1350000, upperLimit: 1850000, rate: 20, description: 'Higher bracket', descriptionBn: 'উচ্চ কর ধাপ' },
      { sequence: 6, range: 'Remaining Balance', rangeBn: 'অবশিষ্ট মোট আয়ের ওপর', lowerLimit: 1850000, upperLimit: null, rate: 25, description: 'Top marginal progressive bracket', descriptionBn: 'সর্বোচ্চ প্রান্তিক প্রগতিশীল কর হার' },
    ],
    minimumTaxes: [
      {
        id: 'dhaka_chattogram',
        area: 'Dhaka & Chattogram City Corporations',
        areaBn: 'ঢাকা ও চট্টগ্রাম সিটি কর্পোরেশন এলাকা',
        amount: 5000,
        formatted: '৳ 5,00,000',
        formattedBn: '৳ ৫,০০০',
        description: 'North Dhaka, South Dhaka, and Chattogram City Corporation areas',
        descriptionBn: 'ঢাকা উত্তর, ঢাকা দক্ষিণ ও চট্টগ্রাম সিটি কর্পোরেশন এলাকা'
      },
      {
        id: 'other_city_corporation',
        area: 'Other City Corporation Areas',
        areaBn: 'অন্যান্য সিটি কর্পোরেশন এলাকা',
        amount: 4000,
        formatted: '৳ 4,000',
        formattedBn: '৳ ৪,০০০',
        description: 'Rajshahi, Khulna, Sylhet, Barishal, Rangpur, Cumilla, Gazipur, Narayanganj, Mymensingh',
        descriptionBn: 'রাজশাহী, খুলনা, সিলেট, বরিশাল, রংপুর, কুমিল্লা, গাজীপুর, নারায়ণগঞ্জ, ময়মনসিংহ'
      },
      {
        id: 'non_city_corporation',
        area: 'Non-City / Municipalities / Rural Areas',
        areaBn: 'সিটি কর্পোরেশন বহির্ভূত / পৌরসভা / গ্রামীণ এলাকা',
        amount: 3000,
        formatted: '৳ 3,000',
        formattedBn: '৳ ৩,০০০',
        description: 'All areas outside designated city corporation boundaries',
        descriptionBn: 'সিটি কর্পোরেশন সীমানার বাইরে অবস্থিত সকল এলাকা'
      },
    ],
    rebateRules: {
      section: 'Section 78, Income Tax Act 2023',
      sectionBn: 'ধারা ৭৮, আয়কর আইন ২০২৩',
      rate: 15,
      rateFormatted: '15% of allowable investment',
      rateFormattedBn: 'অনুমোদিত বিনিয়োগের ১৫%',
      incomeCeilingPercentage: 20,
      incomeCeilingFormatted: '20% of net taxable income',
      incomeCeilingFormattedBn: 'করযোগ্য আয়ের ২০%',
      maxStatutoryCap: 1000000,
      maxStatutoryCapFormatted: '৳ 10,00,000',
      maxStatutoryCapFormattedBn: '৳ ১০,০০,০০০',
      dpsAnnualCap: 120000,
      dpsAnnualCapFormatted: '৳ 1,20,000 / year',
      dpsAnnualCapFormattedBn: 'বাৎসরিক ৳ ১,২০,০০০',
      allowableInstruments: ['Deposit Pension Scheme (DPS)', 'Sanchayapatra (Savings Certificates)', 'Life Insurance Premium', 'Stock Market & Listed Mutual Funds', 'Recognized Provident Fund (GPF/EPF)', 'Government Benevolent Fund'],
      allowableInstrumentsBn: ['ডিপোজিট পেনশন স্কিম (DPS)', 'সঞ্চয়পত্র ক্রয়', 'জীবন বীমার প্রিমিয়াম', 'পুঁজিবাজারের শেয়ার ও মিউচুয়াল ফান্ড', 'স্বীকৃত ভবিষ্যৎ তহবিল (GPF/RPF)', 'সরকারি কল্যাণ তহবিল ও যৌথ বীমা'],
    },
    surchargeRules: {
      section: 'Finance Act 2024 Section 4',
      sectionBn: 'অর্থ আইন ২০২৪-এর ৪ ধারা',
      wealthThreshold: 40000000,
      wealthThresholdFormatted: '৳ 4 Crore',
      wealthThresholdFormattedBn: '৳ ৪ কোটি',
      tiers: [
        { tier: 'Up to ৳ 4 Crore', tierBn: '৪ কোটি টাকা পর্যন্ত', rate: 0, description: 'No Surcharge', descriptionBn: 'কোনো সারচার্জ নেই' },
        { tier: 'Above ৳ 4 Crore to ৳ 10 Crore', tierBn: '৪ কোটি থেকে ১০ কোটি পর্যন্ত', rate: 10, description: '10% on calculated tax', descriptionBn: 'হিসাবকৃত করের ওপর ১০%' },
        { tier: 'Above ৳ 10 Crore to ৳ 20 Crore', tierBn: '১০ কোটি থেকে ২০ কোটি পর্যন্ত', rate: 20, description: '20% on calculated tax', descriptionBn: 'হিসাবকৃত করের ওপর ২০%' },
        { tier: 'Above ৳ 20 Crore to ৳ 50 Crore', tierBn: '২০ কোটি থেকে ৫০ কোটি পর্যন্ত', rate: 30, description: '30% on calculated tax', descriptionBn: 'হিসাবকৃত করের ওপর ৩০%' },
        { tier: 'Exceeding ৳ 50 Crore', tierBn: '৫০ কোটি টাকার অধিক', rate: 35, description: '35% on calculated tax', descriptionBn: 'হিসাবকৃত করের ওপর ৩৫%' },
      ],
      assetTriggers: [
        { trigger: 'Owning more than 1 motor vehicle / car', triggerBn: 'একাধিক মোটরগাড়ির মালিকানা', rate: 10, description: 'Triggers minimum 10% surcharge regardless of whether net wealth is below ৳4 Crore', descriptionBn: 'মোট নিট সম্পদ ৪ কোটি টাকার নিচে হলেও ন্যূনতম ১০% সারচার্জ প্রযোজ্য' },
        { trigger: 'Owning residential property exceeding 8,000 sq ft', triggerBn: '৮,০০০ বর্গফুটের অধিক গৃহ-সম্পত্তি', rate: 10, description: 'Triggers minimum 10% surcharge', descriptionBn: 'সিটি এলাকায় ৮,০০০ বর্গফুটের ফ্ল্যাট বা বাড়ি থাকলে ন্যূনতম ১০% সারচার্জ' },
      ],
    },
    salaryDeductions: {
      houseRent: 'Lower of actual received, 50% of basic salary, or ৳ 3,00,000/year',
      houseRentBn: 'প্রাপ্ত বাড়ি ভাড়া, মূল বেতনের ৫০% অথবা বাৎসরিক ৩,০০,০০০ টাকার মধ্যে যেটি কম',
      medical: 'Lower of actual received, 10% of basic salary, or ৳ 1,20,000/year',
      medicalBn: 'প্রাপ্ত চিকিৎসা ভাতা, মূল বেতনের ১০% অথবা বাৎসরিক ১,২০,০০০ টাকার মধ্যে যেটি কম',
      conveyance: 'Lower of actual received or ৳ 30,000/year',
      conveyanceBn: 'বাৎসরিক সর্বোচ্চ ৩০,০০০ টাকা পর্যন্ত করমুক্ত',
    },
    officialDocuments: [
      {
        title: 'Income Tax Act 2023 (Act No. 18 of 2023)',
        titleBn: 'আয়কর আইন ২০২৩ (২০২৩ সনের ১৮ নং আইন)',
        reference: 'ACT-18-2023',
        authority: 'National Board of Revenue (NBR)',
        authorityBn: 'জাতীয় রাজস্ব বোর্ড (NBR)',
        url: 'https://nbr.gov.bd',
        date: 'June 2023',
        dateBn: 'জুন ২০২৩',
      },
      {
        title: 'Finance Act 2024',
        titleBn: 'অর্থ আইন ২০২৪ (২০২৪ সনের ১২ নং আইন)',
        reference: 'Act No. 12 of 2024',
        authority: 'Ministry of Finance & NBR',
        authorityBn: 'অর্থ মন্ত্রণালয় ও জাতীয় রাজস্ব বোর্ড',
        url: 'https://nbr.gov.bd',
        date: 'June 2024',
        dateBn: 'জুন ২০২৪',
      },
      {
        title: 'NBR Paripatra 2024-2025 (Income Tax Clarification Manual)',
        titleBn: 'এনবিআর আয়কর পরিপত্র ২০২৪-২০২৫ (আয়কর ব্যাখ্যা নির্দেশিকা)',
        reference: 'Paripatra 1 (Income Tax)',
        authority: 'NBR Tax Policy Wing',
        authorityBn: 'জাতীয় রাজস্ব বোর্ড কর নীতি উইং',
        url: 'https://nbr.gov.bd',
        date: 'July 2024',
        dateBn: 'জুলাই ২০২৪',
      },
    ],
  },

  '2025-2026': {
    assessmentYear: '2025-2026',
    incomeYear: '2024-2025',
    status: 'Upcoming / Provisional Planning Rules',
    statusBn: 'আসন্ন / সম্ভাব্য কর পরিকল্পনা বিধিমালা',
    act: 'Income Tax Act 2023 & Finance Act 2025 Projections',
    actBn: 'আয়কর আইন ২০২৩ ও অর্থ আইন ২০২৫ পূর্বাভাস কাঠামো',
    gazetteRef: 'Provisional Fiscal Framework',
    gazetteRefBn: 'সম্ভাব্য আর্থিক কাঠামো',
    lastVerified: 'September 2024',
    generalThreshold: 350000,
    exemptionThresholds: [
      {
        id: 'general',
        category: 'General Individual (Male)',
        categoryBn: 'সাধারণ ব্যক্তি করদাতা (পুরুষ)',
        limit: 350000,
        formatted: '৳ 3,50,000',
        formattedBn: '৳ ৩,৫০,০০০',
        description: 'Provisional standard threshold',
        descriptionBn: 'সম্ভাব্য প্রারম্ভিক করমুক্ত সীমা'
      },
      {
        id: 'female',
        category: 'Female Taxpayers',
        categoryBn: 'মহিলা করদাতা',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'Provisional threshold',
        descriptionBn: 'মহিলা করদাতাদের জন্য সম্ভাব্য সীমা'
      },
      {
        id: 'seniorCitizen',
        category: 'Senior Citizens (Age 65+)',
        categoryBn: 'প্রবীণ নাগরিক (বয়স ৬৫ বা তদূর্ধ্ব)',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'Provisional threshold',
        descriptionBn: '৬৫ বা তদূর্ধ্ব প্রবীণদের সম্ভাব্য সীমা'
      },
      {
        id: 'thirdGender',
        category: 'Third Gender Taxpayers',
        categoryBn: 'তৃতীয় লিঙ্গের করদাতা',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'Provisional threshold',
        descriptionBn: 'তৃতীয় লিঙ্গ সম্প্রদায়ের জন্য করমুক্ত সীমা'
      },
      {
        id: 'disabled',
        category: 'Persons with Disabilities',
        categoryBn: 'প্রতিবন্ধী ব্যক্তি করদাতা',
        limit: 475000,
        formatted: '৳ 4,75,000',
        formattedBn: '৳ ৪,৭৫,০০০',
        description: 'Provisional threshold',
        descriptionBn: 'প্রতিবন্ধী ব্যক্তিদের সম্ভাব্য করমুক্ত সীমা'
      },
      {
        id: 'freedomFighter',
        category: 'Gazetted Freedom Fighters',
        categoryBn: 'গেজেটভুক্ত যুদ্ধাহত বীর মুক্তিযোদ্ধা',
        limit: 500000,
        formatted: '৳ 5,00,000',
        formattedBn: '৳ ৫,০০,০০০',
        description: 'Provisional threshold',
        descriptionBn: 'বীর মুক্তিযোদ্ধাদের জন্য বিশেষ করমুক্ত সীমা'
      },
      {
        id: 'parentOfDisabled',
        category: 'Parent/Guardian of Disabled Child',
        categoryBn: 'প্রতিবন্ধী সন্তানের পিতা/মাতা বা অভিভাবক',
        limit: 50000,
        formatted: '+ ৳ 50,000 / child',
        formattedBn: '+ ৳ ৫০,০০০ / সন্তান',
        description: 'Additional allowance per disabled dependent child',
        descriptionBn: 'প্রতিটি প্রতিবন্ধী সন্তানের জন্য অতিরিক্ত করমুক্ত সুবিধা'
      },
    ],
    slabs: [
      { sequence: 1, range: 'First ৳ 3,50,000*', rangeBn: 'প্রথম ৩,৫০,০০০ টাকা পর্যন্ত*', lowerLimit: 0, upperLimit: 350000, rate: 0, description: 'Tax-free exemption limit', descriptionBn: 'করমুক্ত আয়ের প্রারম্ভিক সীমা' },
      { sequence: 2, range: 'Next ৳ 1,00,000', rangeBn: 'পরবর্তী ১,০০,০০০ টাকা পর্যন্ত', lowerLimit: 350000, upperLimit: 450000, rate: 5, description: 'Lowest progressive taxable tier', descriptionBn: 'সর্বনিম্ন প্রগতিশীল করযোগ্য ধাপ' },
      { sequence: 3, range: 'Next ৳ 4,00,000', rangeBn: 'পরবর্তী ৪,০০,০০০ টাকা পর্যন্ত', lowerLimit: 450000, upperLimit: 850000, rate: 10, description: 'Middle bracket', descriptionBn: 'মধ্যবর্তী কর ধাপ' },
      { sequence: 4, range: 'Next ৳ 5,00,000', rangeBn: 'পরবর্তী ৫,০০,০০০ টাকা পর্যন্ত', lowerLimit: 850000, upperLimit: 1350000, rate: 15, description: 'Upper-middle bracket', descriptionBn: 'উচ্চ-মধ্যবর্তী কর ধাপ' },
      { sequence: 5, range: 'Next ৳ 5,00,000', rangeBn: 'পরবর্তী ৫,০০,০০০ টাকা পর্যন্ত', lowerLimit: 1350000, upperLimit: 1850000, rate: 20, description: 'Higher bracket', descriptionBn: 'উচ্চ কর ধাপ' },
      { sequence: 6, range: 'Remaining Balance', rangeBn: 'অবশিষ্ট মোট আয়ের ওপর', lowerLimit: 1850000, upperLimit: null, rate: 25, description: 'Top marginal progressive bracket', descriptionBn: 'সর্বোচ্চ প্রান্তিক কর হার' },
    ],
    minimumTaxes: [
      {
        id: 'dhaka_chattogram',
        area: 'Dhaka & Chattogram City Corporations',
        areaBn: 'ঢাকা ও চট্টগ্রাম সিটি কর্পোরেশন এলাকা',
        amount: 5000,
        formatted: '৳ 5,000',
        formattedBn: '৳ ৫,০০০',
        description: 'Statutory city corporation minimum',
        descriptionBn: 'সংবিধিবদ্ধ সিটি কর্পোরেশন ন্যূনতম কর'
      },
      {
        id: 'other_city_corporation',
        area: 'Other City Corporation Areas',
        areaBn: 'অন্যান্য সিটি কর্পোরেশন এলাকা',
        amount: 4000,
        formatted: '৳ 4,000',
        formattedBn: '৳ ৪,০০০',
        description: 'Statutory divisional city minimum',
        descriptionBn: 'বিভাগীয় অন্যান্য সিটি কর্পোরেশন এলাকার জন্য'
      },
      {
        id: 'non_city_corporation',
        area: 'Non-City / Municipalities / Rural Areas',
        areaBn: 'সিটি কর্পোরেশন বহির্ভূত / পৌরসভা / গ্রামীণ এলাকা',
        amount: 3000,
        formatted: '৳ 3,000',
        formattedBn: '৳ ৩,০০০',
        description: 'Statutory rural minimum',
        descriptionBn: 'পৌরসভা ও গ্রামীণ এলাকার জন্য সংবিধিবদ্ধ ন্যূনতম কর'
      },
    ],
    rebateRules: {
      section: 'Section 78, Income Tax Act 2023',
      sectionBn: 'ধারা ৭৮, আয়কর আইন ২০২৩',
      rate: 15,
      rateFormatted: '15% of allowable investment',
      rateFormattedBn: 'অনুমোদিত বিনিয়োগের ১৫%',
      incomeCeilingPercentage: 20,
      incomeCeilingFormatted: '20% of net taxable income',
      incomeCeilingFormattedBn: 'করযোগ্য আয়ের ২০%',
      maxStatutoryCap: 1000000,
      maxStatutoryCapFormatted: '৳ 10,00,000',
      maxStatutoryCapFormattedBn: '৳ ১০,০০,০০০',
      dpsAnnualCap: 120000,
      dpsAnnualCapFormatted: '৳ 1,20,000 / year',
      dpsAnnualCapFormattedBn: 'বাৎসরিক ৳ ১,২০,০০০',
      allowableInstruments: ['DPS', 'Sanchayapatra', 'Life Insurance', 'Stock Market', 'Provident Fund', 'Benevolent Fund'],
      allowableInstrumentsBn: ['ডিপিএস', 'সঞ্চয়পত্র', 'জীবন বীমা', 'শেয়ার ও মিউচুয়াল ফান্ড', 'ভবিষ্যৎ তহবিল (GPF)', 'কল্যাণ তহবিল'],
    },
    surchargeRules: {
      section: 'Finance Act Statutory Framework',
      sectionBn: 'অর্থ আইন সংবিধিবদ্ধ কাঠামো',
      wealthThreshold: 40000000,
      wealthThresholdFormatted: '৳ 4 Crore',
      wealthThresholdFormattedBn: '৳ ৪ কোটি',
      tiers: [
        { tier: 'Up to ৳ 4 Crore', tierBn: '৪ কোটি টাকা পর্যন্ত', rate: 0, description: 'No Surcharge', descriptionBn: 'কোনো সারচার্জ নেই' },
        { tier: 'Above ৳ 4 Crore to ৳ 10 Crore', tierBn: '৪ কোটি থেকে ১০ কোটি পর্যন্ত', rate: 10, description: '10% on calculated tax', descriptionBn: 'হিসাবকৃত করের ১০%' },
        { tier: 'Above ৳ 10 Crore to ৳ 20 Crore', tierBn: '১০ কোটি থেকে ২০ কোটি পর্যন্ত', rate: 20, description: '20% on calculated tax', descriptionBn: 'হিসাবকৃত করের ২০%' },
        { tier: 'Above ৳ 20 Crore to ৳ 50 Crore', tierBn: '২০ কোটি থেকে ৫০ কোটি পর্যন্ত', rate: 30, description: '30% on calculated tax', descriptionBn: 'হিসাবকৃত করের ৩০%' },
        { tier: 'Exceeding ৳ 50 Crore', tierBn: '৫০ কোটি টাকার অধিক', rate: 35, description: '35% on calculated tax', descriptionBn: 'হিসাবকৃত করের ৩৫%' },
      ],
      assetTriggers: [
        { trigger: 'Owning more than 1 motor vehicle', triggerBn: 'একাধিক মোটরগাড়ি থাকলে', rate: 10, description: '10% minimum surcharge', descriptionBn: 'ন্যূনতম ১০% সারচার্জ প্রযোজ্য' },
        { trigger: 'Owning residential property exceeding 8,000 sq ft', triggerBn: '৮,০০০ বর্গফুটের অধিক বাড়ি বা ফ্ল্যাট থাকলে', rate: 10, description: '10% minimum surcharge', descriptionBn: 'ন্যূনতম ১০% সারচার্জ প্রযোজ্য' },
      ],
    },
    salaryDeductions: {
      houseRent: 'Lower of actual received, 50% of basic salary, or ৳ 3,00,000/year',
      houseRentBn: 'প্রাপ্ত বাড়ি ভাড়া, মূল বেতনের ৫০% অথবা বাৎসরিক ৩,০০,০০০ টাকার মধ্যে যেটি কম',
      medical: 'Lower of actual received, 10% of basic salary, or ৳ 1,20,000/year',
      medicalBn: 'প্রাপ্ত চিকিৎসা ভাতা, মূল বেতনের ১০% অথবা বাৎসরিক ১,২০,০০০ টাকার মধ্যে যেটি কম',
      conveyance: 'Lower of actual received or ৳ 30,000/year',
      conveyanceBn: 'বাৎসরিক সর্বোচ্চ ৩০,০০০ টাকা পর্যন্ত করমুক্ত',
    },
    officialDocuments: [
      {
        title: 'Income Tax Act 2023 & Planning Framework',
        titleBn: 'আয়কর আইন ২০২৩ ও পরিকল্পনা কাঠামো',
        reference: 'ACT-18-2023',
        authority: 'National Board of Revenue (NBR)',
        authorityBn: 'জাতীয় রাজস্ব বোর্ড (NBR)',
        url: 'https://nbr.gov.bd',
        date: 'Provisional',
        dateBn: 'সম্ভাব্য',
      },
    ],
  },

  '2023-2024': {
    assessmentYear: '2023-2024',
    incomeYear: '2022-2023',
    status: 'Historical (Initial Income Tax Act 2023 Implementation)',
    statusBn: 'ঐতিহাসিক (আয়কর আইন ২০২৩ এর প্রথম বাস্তবায়ন)',
    act: 'Income Tax Act 2023 & Finance Act 2023',
    actBn: 'আয়কর আইন ২০২৩ ও অর্থ আইন ২০২৩',
    gazetteRef: 'Bangladesh Gazette Extra Ordinary, June 2023',
    gazetteRefBn: 'বাংলাদেশ গেজেট অতিরিক্ত, জুন ২০২৩',
    lastVerified: 'September 2024',
    generalThreshold: 350000,
    exemptionThresholds: [
      {
        id: 'general',
        category: 'General Individual (Male)',
        categoryBn: 'সাধারণ ব্যক্তি করদাতা (পুরুষ)',
        limit: 350000,
        formatted: '৳ 3,50,000',
        formattedBn: '৳ ৩,৫০,০০০',
        description: 'Raised from ৳3,00,000 under previous ordinance',
        descriptionBn: 'পূর্ববর্তী অধ্যাদেশের ৩,০০,০০০ টাকা থেকে বৃদ্ধিপ্রাপ্ত'
      },
      {
        id: 'female',
        category: 'Female Taxpayers',
        categoryBn: 'মহিলা করদাতা',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'Raised from ৳3,50,000',
        descriptionBn: 'পূর্বের ৩,৫০,০০০ টাকা থেকে বৃদ্ধি পেয়ে ৪,০০,০০০ টাকা'
      },
      {
        id: 'seniorCitizen',
        category: 'Senior Citizens (Age 65+)',
        categoryBn: 'প্রবীণ নাগরিক (বয়স ৬৫ বা তদূর্ধ্ব)',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'Raised from ৳3,50,000',
        descriptionBn: '৬৫ বছর বা তদূর্ধ্ব প্রবীণদের জন্য বৃদ্ধিপ্রাপ্ত সীমা'
      },
      {
        id: 'thirdGender',
        category: 'Third Gender Taxpayers',
        categoryBn: 'তৃতীয় লিঙ্গের করদাতা',
        limit: 400000,
        formatted: '৳ 4,00,000',
        formattedBn: '৳ ৪,০০,০০০',
        description: 'Introduced ৳4,00,000 parity threshold',
        descriptionBn: '৪,০০,০০০ টাকার সমতাভিত্তিক করমুক্ত সীমা প্রবর্তন'
      },
      {
        id: 'disabled',
        category: 'Persons with Disabilities',
        categoryBn: 'প্রতিবন্ধী ব্যক্তি করদাতা',
        limit: 475000,
        formatted: '৳ 4,75,000',
        formattedBn: '৳ ৪,৭৫,০০০',
        description: 'Raised from ৳4,50,000',
        descriptionBn: 'পূর্বের ৪,৫০,০০০ টাকা থেকে বৃদ্ধিপ্রাপ্ত'
      },
      {
        id: 'freedomFighter',
        category: 'Gazetted Freedom Fighters',
        categoryBn: 'গেজেটভুক্ত যুদ্ধাহত বীর মুক্তিযোদ্ধা',
        limit: 500000,
        formatted: '৳ 5,00,000',
        formattedBn: '৳ ৫,০০,০০০',
        description: 'Raised from ৳4,75,000',
        descriptionBn: 'পূর্বের ৪,৭৫,০০০ টাকা থেকে বৃদ্ধিপ্রাপ্ত'
      },
      {
        id: 'parentOfDisabled',
        category: 'Parent/Guardian of Disabled Child',
        categoryBn: 'প্রতিবন্ধী সন্তানের পিতা/মাতা বা অভিভাবক',
        limit: 50000,
        formatted: '+ ৳ 50,000 / child',
        formattedBn: '+ ৳ ৫০,০০০ / সন্তান',
        description: 'Additional dependent deduction per child',
        descriptionBn: 'প্রতিটি প্রতিবন্ধী সন্তানের জন্য অতিরিক্ত করমুক্ত সীমা'
      },
    ],
    slabs: [
      { sequence: 1, range: 'First ৳ 3,50,000*', rangeBn: 'প্রথম ৩,৫০,০০০ টাকা পর্যন্ত*', lowerLimit: 0, upperLimit: 350000, rate: 0, description: 'Tax-free exemption limit', descriptionBn: 'করমুক্ত আয়ের প্রারম্ভিক সীমা' },
      { sequence: 2, range: 'Next ৳ 1,00,000', rangeBn: 'পরবর্তী ১,০০,০০০ টাকা পর্যন্ত', lowerLimit: 350000, upperLimit: 450000, rate: 5, description: '5% initial taxable bracket', descriptionBn: '৫% প্রাথমিক করযোগ্য ধাপ' },
      { sequence: 3, range: 'Next ৳ 3,00,000', rangeBn: 'পরবর্তী ৩,০০,০০০ টাকা পর্যন্ত', lowerLimit: 450000, upperLimit: 750000, rate: 10, description: '10% middle bracket (was ৳3L in 2023)', descriptionBn: '১০% মধ্যবর্তী কর ধাপ (২০২৩ সালে ৩ লাখ টাকা পর্যন্ত ছিল)' },
      { sequence: 4, range: 'Next ৳ 4,00,000', rangeBn: 'পরবর্তী ৪,০০,০০০ টাকা পর্যন্ত', lowerLimit: 750000, upperLimit: 1150000, rate: 15, description: '15% bracket', descriptionBn: '১৫% কর ধাপ' },
      { sequence: 5, range: 'Next ৳ 5,00,000', rangeBn: 'পরবর্তী ৫,০০,০০০ টাকা পর্যন্ত', lowerLimit: 1150000, upperLimit: 1650000, rate: 20, description: '20% bracket', descriptionBn: '২০% কর ধাপ' },
      { sequence: 6, range: 'Remaining Balance', rangeBn: 'অবশিষ্ট মোট আয়ের ওপর', lowerLimit: 1650000, upperLimit: null, rate: 25, description: '25% top bracket', descriptionBn: '২৫% সর্বোচ্চ প্রান্তিক কর ধাপ' },
    ],
    minimumTaxes: [
      {
        id: 'dhaka_chattogram',
        area: 'Dhaka & Chattogram City Corporations',
        areaBn: 'ঢাকা ও চট্টগ্রাম সিটি কর্পোরেশন এলাকা',
        amount: 5000,
        formatted: '৳ 5,000',
        formattedBn: '৳ ৫,০০০',
        description: 'Statutory city corporation minimum',
        descriptionBn: 'সংবিধিবদ্ধ সিটি কর্পোরেশন ন্যূনতম কর'
      },
      {
        id: 'other_city_corporation',
        area: 'Other City Corporation Areas',
        areaBn: 'অন্যান্য সিটি কর্পোরেশন এলাকা',
        amount: 4000,
        formatted: '৳ 4,000',
        formattedBn: '৳ ৪,০০০',
        description: 'Statutory divisional city minimum',
        descriptionBn: 'অন্যান্য সিটি কর্পোরেশনের ন্যূনতম কর'
      },
      {
        id: 'non_city_corporation',
        area: 'Non-City / Municipalities / Rural Areas',
        areaBn: 'সিটি কর্পোরেশন বহির্ভূত / পৌরসভা / গ্রামীণ এলাকা',
        amount: 3000,
        formatted: '৳ 3,000',
        formattedBn: '৳ ৩,০০০',
        description: 'Statutory rural minimum',
        descriptionBn: 'পৌরসভা ও গ্রামীণ এলাকার জন্য ন্যূনতম কর'
      },
    ],
    rebateRules: {
      section: 'Section 78, Income Tax Act 2023',
      sectionBn: 'ধারা ৭৮, আয়কর আইন ২০২৩',
      rate: 15,
      rateFormatted: '15% flat rate',
      rateFormattedBn: 'একক ১৫% কর রেয়াত',
      incomeCeilingPercentage: 20,
      incomeCeilingFormatted: '20% of taxable income',
      incomeCeilingFormattedBn: 'করযোগ্য আয়ের ২০%',
      maxStatutoryCap: 1000000,
      maxStatutoryCapFormatted: '৳ 10,00,000',
      maxStatutoryCapFormattedBn: '৳ ১০,০০,০০০',
      dpsAnnualCap: 120000,
      dpsAnnualCapFormatted: '৳ 1,20,000 / year',
      dpsAnnualCapFormattedBn: 'বাৎসরিক ৳ ১,২০,০০০',
      allowableInstruments: ['DPS', 'Sanchayapatra', 'Life Insurance', 'Stock Market', 'Provident Fund'],
      allowableInstrumentsBn: ['ডিপিএস', 'সঞ্চয়পত্র', 'জীবন বীমা', 'পুঁজিবাজারের শেয়ার ও ফান্ড', 'ভবিষ্যৎ তহবিল'],
    },
    surchargeRules: {
      section: 'Finance Act 2023',
      sectionBn: 'অর্থ আইন ২০২৩',
      wealthThreshold: 40000000,
      wealthThresholdFormatted: '৳ 4 Crore',
      wealthThresholdFormattedBn: '৳ ৪ কোটি',
      tiers: [
        { tier: 'Up to ৳ 4 Crore', tierBn: '৪ কোটি টাকা পর্যন্ত', rate: 0, description: 'No Surcharge', descriptionBn: 'কোনো সারচার্জ নেই' },
        { tier: 'Above ৳ 4 Crore to ৳ 10 Crore', tierBn: '৪ কোটি থেকে ১০ কোটি পর্যন্ত', rate: 10, description: '10% on calculated tax', descriptionBn: 'হিসাবকৃত করের ১০%' },
        { tier: 'Above ৳ 10 Crore to ৳ 20 Crore', tierBn: '১০ কোটি থেকে ২০ কোটি পর্যন্ত', rate: 20, description: '20% on calculated tax', descriptionBn: 'হিসাবকৃত করের ২০%' },
        { tier: 'Above ৳ 20 Crore to ৳ 50 Crore', tierBn: '২০ কোটি থেকে ৫০ কোটি পর্যন্ত', rate: 30, description: '30% on calculated tax', descriptionBn: 'হিসাবকৃত করের ৩০%' },
        { tier: 'Exceeding ৳ 50 Crore', tierBn: '৫০ কোটি টাকার অধিক', rate: 35, description: '35% on calculated tax', descriptionBn: 'হিসাবকৃত করের ৩৫%' },
      ],
      assetTriggers: [
        { trigger: 'Owning more than 1 motor vehicle', triggerBn: 'একাধিক মোটরগাড়ির মালিকানা', rate: 10, description: '10% minimum surcharge', descriptionBn: 'ন্যূনতম ১০% সারচার্জ প্রযোজ্য' },
      ],
    },
    salaryDeductions: {
      houseRent: 'Lower of actual received, 50% of basic salary, or ৳ 3,00,000/year',
      houseRentBn: 'প্রাপ্ত বাড়ি ভাড়া, মূল বেতনের ৫০% অথবা বাৎসরিক ৩,০০,০০০ টাকার মধ্যে যেটি কম',
      medical: 'Lower of actual received, 10% of basic salary, or ৳ 1,20,000/year',
      medicalBn: 'প্রাপ্ত চিকিৎসা ভাতা, মূল বেতনের ১০% অথবা বাৎসরিক ১,২০,০০০ টাকার মধ্যে যেটি কম',
      conveyance: 'Lower of actual received or ৳ 30,000/year',
      conveyanceBn: 'বাৎসরিক সর্বোচ্চ ৩০,০০০ টাকা পর্যন্ত করমুক্ত',
    },
    officialDocuments: [
      {
        title: 'Income Tax Act 2023 (Act No. 18 of 2023)',
        titleBn: 'আয়কর আইন ২০২৩ (২০২৩ সনের ১৮ নং আইন)',
        reference: 'ACT-18-2023',
        authority: 'National Board of Revenue (NBR)',
        authorityBn: 'জাতীয় রাজস্ব বোর্ড (NBR)',
        url: 'https://nbr.gov.bd',
        date: 'June 2023',
        dateBn: 'জুন ২০২৩',
      },
    ],
  },
};

export const WHATS_CHANGED_TIMELINE = [
  {
    id: 'change-1',
    topic: 'Tax-Free Exemption Thresholds',
    topicBn: 'করমুক্ত আয়ের প্রারম্ভিক সীমা',
    title: 'Increase in Base Tax-Free Threshold from ৳3.0 Lakh to ৳3.5 Lakh',
    titleBn: 'সাধারণ করমুক্ত সীমা ৩.০ লাখ থেকে বাড়িয়ে ৩.৫০ লাখ টাকায় উন্নীতকরণ',
    effectiveAY: '2023-2024 onwards',
    effectiveAYBn: 'করবর্ষ ২০২৩–২৪ থেকে কার্যকর',
    oldRule: 'General Individual threshold was ৳ 3,00,000 (Female/Senior: ৳ 3,50,000) under the Income Tax Ordinance 1984.',
    oldRuleBn: 'আয়কর অধ্যাদেশ ১৯৮৪-এর অধীনে সাধারণ করদাতার করমুক্ত সীমা ছিল ৩,০০,০০০ টাকা (নারী/প্রবীণ: ৩,৫০,০০০ টাকা)।',
    newRule: 'General Individual threshold increased to ৳ 3,50,000 (Female/Senior/Third Gender: ৳ 4,00,000, Disabled: ৳ 4,75,000, Freedom Fighters: ৳ 5,00,000).',
    newRuleBn: 'আয়কর আইন ২০২৩-এ সাধারণ পুরুষের করমুক্ত সীমা বাড়িয়ে ৩,৫০,০০০ টাকা এবং নারী/প্রবীণ/তৃতীয় লিঙ্গের জন্য ৪,০০,০০০ টাকা করা হয়েছে।',
    officialSource: 'Income Tax Act 2023 & Finance Act 2023 First Schedule',
    officialSourceBn: 'আয়কর আইন ২০২৩ ও অর্থ আইন ২০২৩ প্রথম তফসিল',
    authority: 'National Board of Revenue (NBR)',
    authorityBn: 'জাতীয় রাজস্ব বোর্ড (NBR)',
    impact: 'Reduces tax burden by saving up to ৳2,500 for entry-level taxpayers.',
    impactBn: 'প্রারম্ভিক করদাতাদের করের বোঝা হ্রাস পায় এবং আয়ের প্রথম ধাপে কর সাশ্রয় নিশ্চিত হয়।',
    badge: 'Threshold Change',
    badgeBn: 'করমুক্ত সীমা বৃদ্ধি',
    badgeColor: 'emerald',
  },
  {
    id: 'change-2',
    topic: 'Tax Slabs & Tier Widths',
    topicBn: 'কর ধাপ ও স্ল্যাবের ব্যাপ্তি',
    title: 'Expansion of Middle Tax Slabs in Finance Act 2024',
    titleBn: 'অর্থ আইন ২০২৪-এ মধ্যম কর ধাপসমূহের ব্যাপ্তি সম্প্রসারণ',
    effectiveAY: '2024-2025',
    effectiveAYBn: 'করবর্ষ ২০২৪–২৫',
    oldRule: '10% slab was applied to the next ৳ 3,00,000; 15% slab was applied to the next ৳ 4,00,000.',
    oldRuleBn: '১০% কর ধাপটি ছিল পরবর্তী ৩,০০,০০০ টাকার ওপর এবং ১৫% কর ধাপটি ছিল পরবর্তী ৪,০০,০০০ টাকার ওপর।',
    newRule: '10% slab expanded to next ৳ 4,00,000; 15% slab expanded to next ৳ 5,00,000; 20% slab expanded to next ৳ 5,00,000.',
    newRuleBn: '১০% ধাপটি বাড়িয়ে পরবর্তী ৪,০০,০০০ টাকা এবং ১৫% ও ২০% ধাপ দুটি বাড়িয়ে পরবর্তী ৫,০০,০০০ টাকা পর্যন্ত বিস্তৃত করা হয়েছে।',
    officialSource: 'Finance Act 2024, Section 2 & NBR Paripatra 2024-2025',
    officialSourceBn: 'অর্থ আইন ২০২৪, ধারা ২ এবং এনবিআর আয়কর পরিপত্র ২০২৪-২০২৫',
    authority: 'National Board of Revenue (NBR)',
    authorityBn: 'জাতীয় রাজস্ব বোর্ড (NBR)',
    impact: 'Taxpayers earning between ৳8.5L and ৳18.5L pay lower marginal tax on expanded brackets.',
    impactBn: 'সাড়ে ৮ লাখ থেকে সাড়ে ১৮ লাখ টাকা উপার্জনকারী করদাতারা বিস্তৃত ধাপে কম হারে কর পরিশোধের সুবিধা পাচ্ছেন।',
    badge: 'Slab Modification',
    badgeBn: 'কর ধাপ সংস্কার',
    badgeColor: 'blue',
  },
  {
    id: 'change-3',
    topic: 'Section 78 Investment Rebates',
    topicBn: 'ধারা ৭৮: বিনিয়োগ কর রেয়াত',
    title: 'Simplified Single 15% Rebate Rate with 20% Taxable Income Cap',
    titleBn: '২০% করযোগ্য আয় সীমার সাথে একক ১৫% বিনিয়োগ কর রেয়াত পদ্ধতি',
    effectiveAY: '2023-2024 onwards',
    effectiveAYBn: 'করবর্ষ ২০২৩–২৪ থেকে কার্যকর',
    oldRule: 'Multi-tiered rebate system (15% for income < ৳15L; 10% for income > ৳15L, capped at 25% of taxable income).',
    oldRuleBn: 'পূর্বে আয়ের স্তরভেদে বহুস্তরীয় রেয়াত (১৫ লাখের নিচে ১৫%, উপরে ১০%) এবং ২৫% পর্যন্ত সীমা ছিল।',
    newRule: 'Unified flat 15% rebate rate on allowable investments, capped at the lower of actual investment, 20% of taxable income, or ৳ 10,00,000 max cap.',
    newRuleBn: 'অনুমোদনযোগ্য বিনিয়োগের ওপর একক ১৫% রেয়াত এবং করযোগ্য আয়ের ২০% বা সর্বোচ্চ ১০ লাখ টাকার সীমা নির্ধারণ করা হয়েছে।',
    officialSource: 'Section 78 & Schedule 6 Part 3, Income Tax Act 2023',
    officialSourceBn: 'আয়কর আইন ২০২৩ এর ধারা ৭৮ এবং ষষ্ঠ তফসিল অংশ ৩',
    authority: 'National Board of Revenue (NBR)',
    authorityBn: 'জাতীয় রাজস্ব বোর্ড (NBR)',
    impact: 'Clearer, predictable rebate calculations across all income brackets.',
    impactBn: 'সকল করদাতার জন্য হিসাব আরও স্বচ্ছ, সহজ ও অনুমানযোগ্য হয়েছে।',
    badge: 'Rebate Reform',
    badgeBn: 'রেয়াত পদ্ধতির সংস্কার',
    badgeColor: 'amber',
  },
  {
    id: 'change-4',
    topic: 'Net Wealth Surcharge',
    topicBn: 'নিট সম্পদ সারচার্জ',
    title: 'Surcharge Exemption Ceiling Raised to ৳4 Crore with Specific Asset Triggers',
    titleBn: 'সারচার্জ মুক্ত সীমা বাড়িয়ে ৪ কোটি টাকা নির্ধারণ ও সম্পদ ট্রিগার যুক্তকরণ',
    effectiveAY: '2023-2024 onwards',
    effectiveAYBn: 'করবর্ষ ২০২৩–২৪ থেকে কার্যকর',
    oldRule: 'Surcharge applied starting at ৳ 3 Crore net wealth.',
    oldRuleBn: 'পূর্বে ৩ কোটি টাকার বেশি নিট সম্পদ থাকলেই সারচার্জ কার্যকর হতো।',
    newRule: 'Surcharge threshold raised to ৳ 4 Crore. However, owning 2+ motor vehicles or 8,000+ sq ft property triggers minimum 10% surcharge regardless of wealth amount.',
    newRuleBn: 'সাধারণ সারচার্জ সীমা বাড়িয়ে ৪ কোটি টাকা করা হয়েছে; তবে একাধিক গাড়ি বা ৮,০০০+ বর্গফুট ফ্ল্যাট থাকলে সম্পদ ৪ কোটির কম হলেও ১০% সারচার্জ প্রযোজ্য।',
    officialSource: 'Finance Act 2023 / Finance Act 2024 Section 4',
    officialSourceBn: 'অর্থ আইন ২০২৩ ও অর্থ আইন ২০২৪ এর ৪ ধারা',
    authority: 'National Board of Revenue (NBR)',
    authorityBn: 'জাতীয় রাজস্ব বোর্ড (NBR)',
    impact: 'Exempts middle-class wealth holders while targeting high-value physical luxury assets.',
    impactBn: 'মধ্যবিত্ত সম্পদশালীদের ছাড় দেওয়ার পাশাপাশি বিলাসবহুল সম্পদের মালিকদের ওপর কর সমন্বয় করে।',
    badge: 'Surcharge Restructure',
    badgeBn: 'সারচার্জ পুনর্গঠন',
    badgeColor: 'purple',
  },
  {
    id: 'change-5',
    topic: 'Mandatory Proof of Return (PSR)',
    topicBn: 'রিটার্ন দাখিলের প্রমাণপত্র (PSR)',
    title: 'Expansion to 43+ Statutory Services for Mandatory Return Submission',
    titleBn: '৪৩টির বেশি নাগরিক ও বাণিজ্যিক সেবায় রিটার্ন দাখিলের প্রমাণপত্র বাধ্যতামূলক',
    effectiveAY: '2023-2024 onwards',
    effectiveAYBn: 'করবর্ষ ২০২৩–২৪ থেকে কার্যকর',
    oldRule: 'TIN certificate was sufficient for banking, utility connections, and property registration.',
    oldRuleBn: 'পূর্বে ব্যাংক হিসাব খোলা, ট্রেড লাইসেন্স বা সেবার জন্য কেবল ই-টিআইএন সনদই যথেষ্ট ছিল।',
    newRule: 'Proof of Submission of Return (PSR / Acknowledgment Receipt) is strictly mandatory for 43+ services under Section 264.',
    newRuleBn: 'আয়কর আইন ২০২৩-এর ২৬৪ ধারা অনুযায়ী ঋণ, ক্রেডিট কার্ড, ট্রেড লাইসেন্স ও জমি রেজিস্ট্রেশনে পিএসআর বাধ্যতামূলক করা হয়েছে।',
    officialSource: 'Section 264, Income Tax Act 2023',
    officialSourceBn: 'আয়কর আইন ২০২৩-এর ধারা ২৬৪',
    authority: 'National Board of Revenue (NBR)',
    authorityBn: 'জাতীয় রাজস্ব বোর্ড (NBR)',
    impact: 'Enforces filing compliance for credit cards, trade licenses, land transfers, and corporate executives.',
    impactBn: 'কর ফাঁকি রোধ এবং আনুষ্ঠানিক কর রিটার্ন দাখিলের হার বৃদ্ধিতে কার্যকর ভূমিকা রাখছে।',
    badge: 'Compliance Rule',
    badgeBn: 'আইনগত কমপ্লায়েন্স',
    badgeColor: 'slate',
  },
];
