/**
 * Comprehensive TaxBD Statutory Rules & Historical Comparison Dataset
 * Fully referenced against official Bangladesh Income Tax Act 2023, Finance Acts, and NBR Paripatras.
 */

export const RULES_BY_YEAR = {
  '2024-2025': {
    assessmentYear: '2024-2025',
    incomeYear: '2023-2024',
    status: 'Current Applicable Law (Official)',
    act: 'Income Tax Act 2023 (Act No. 18 of 2023) & Finance Act 2024',
    gazetteRef: 'Bangladesh Gazette Extra Ordinary, 30 June 2024',
    lastVerified: 'September 2024',
    generalThreshold: 350000,
    exemptionThresholds: [
      { id: 'general', category: 'General Individual (Male)', limit: 350000, formatted: '৳ 3,50,000', description: 'Under 65 years without special statutory status' },
      { id: 'female', category: 'Female Taxpayers', limit: 400000, formatted: '৳ 4,00,000', description: 'All female individual taxpayers' },
      { id: 'seniorCitizen', category: 'Senior Citizens (Age 65+)', limit: 400000, formatted: '৳ 4,00,000', description: 'Taxpayers aged 65 years or older as of income year' },
      { id: 'thirdGender', category: 'Third Gender Taxpayers', limit: 400000, formatted: '৳ 4,00,000', description: 'Taxpayers of the third gender community' },
      { id: 'disabled', category: 'Persons with Disabilities', limit: 475000, formatted: '৳ 4,75,000', description: 'Certified physically/mentally challenged individuals' },
      { id: 'freedomFighter', category: 'Gazetted Freedom Fighters', limit: 500000, formatted: '৳ 5,00,000', description: 'Gazetted war-wounded freedom fighters of Bangladesh' },
      { id: 'parentOfDisabled', category: 'Parent/Guardian of Disabled Child', limit: 50000, formatted: '+ ৳ 50,000 / child', description: 'Additional tax-free limit per disabled dependent child' },
    ],
    slabs: [
      { sequence: 1, range: 'First ৳ 3,50,000*', lowerLimit: 0, upperLimit: 350000, rate: 0, description: 'Tax-free exemption limit (based on category)' },
      { sequence: 2, range: 'Next ৳ 1,00,000', lowerLimit: 350000, upperLimit: 450000, rate: 5, description: 'Lowest progressive taxable tier' },
      { sequence: 3, range: 'Next ৳ 4,00,000', lowerLimit: 450000, upperLimit: 850000, rate: 10, description: 'Middle bracket' },
      { sequence: 4, range: 'Next ৳ 5,00,000', lowerLimit: 850000, upperLimit: 1350000, rate: 15, description: 'Upper-middle bracket' },
      { sequence: 5, range: 'Next ৳ 5,00,000', lowerLimit: 1350000, upperLimit: 1850000, rate: 20, description: 'Higher bracket' },
      { sequence: 6, range: 'Remaining Balance', lowerLimit: 1850000, upperLimit: null, rate: 25, description: 'Top marginal progressive bracket' },
    ],
    minimumTaxes: [
      { id: 'dhaka_chattogram', area: 'Dhaka & Chattogram City Corporations', amount: 5000, formatted: '৳ 5,000', description: 'North Dhaka, South Dhaka, and Chattogram City Corporation areas' },
      { id: 'other_city_corporation', area: 'Other City Corporation Areas', amount: 4000, formatted: '৳ 4,00,000', description: 'Rajshahi, Khulna, Sylhet, Barishal, Rangpur, Cumilla, Gazipur, Narayanganj, Mymensingh' },
      { id: 'non_city_corporation', area: 'Non-City / Municipalities / Rural Areas', amount: 3000, formatted: '৳ 3,000', description: 'All areas outside designated city corporation boundaries' },
    ],
    rebateRules: {
      section: 'Section 78, Income Tax Act 2023',
      rate: 15,
      rateFormatted: '15% of allowable investment',
      incomeCeilingPercentage: 20,
      incomeCeilingFormatted: '20% of net taxable income',
      maxStatutoryCap: 1000000,
      maxStatutoryCapFormatted: '৳ 10,00,000',
      dpsAnnualCap: 120000,
      dpsAnnualCapFormatted: '৳ 1,20,000 / year',
      allowableInstruments: ['Deposit Pension Scheme (DPS)', 'Sanchayapatra (Savings Certificates)', 'Life Insurance Premium', 'Stock Market & Listed Mutual Funds', 'Recognized Provident Fund (GPF/EPF)', 'Government Benevolent Fund'],
    },
    surchargeRules: {
      section: 'Finance Act 2024 Section 4',
      wealthThreshold: 40000000,
      wealthThresholdFormatted: '৳ 4 Crore',
      tiers: [
        { tier: 'Up to ৳ 4 Crore', rate: 0, description: 'No Surcharge' },
        { tier: 'Above ৳ 4 Crore to ৳ 10 Crore', rate: 10, description: '10% on calculated tax' },
        { tier: 'Above ৳ 10 Crore to ৳ 20 Crore', rate: 20, description: '20% on calculated tax' },
        { tier: 'Above ৳ 20 Crore to ৳ 50 Crore', rate: 30, description: '30% on calculated tax' },
        { tier: 'Exceeding ৳ 50 Crore', rate: 35, description: '35% on calculated tax' },
      ],
      assetTriggers: [
        { trigger: 'Owning more than 1 motor vehicle / car', rate: 10, description: 'Triggers minimum 10% surcharge regardless of whether net wealth is below ৳4 Crore' },
        { trigger: 'Owning residential property exceeding 8,000 sq ft', rate: 10, description: 'Triggers minimum 10% surcharge' },
      ],
    },
    salaryDeductions: {
      houseRent: 'Lower of actual received, 50% of basic salary, or ৳ 3,00,000/year',
      medical: 'Lower of actual received, 10% of basic salary, or ৳ 1,20,000/year',
      conveyance: 'Lower of actual received or ৳ 30,000/year',
    },
    officialDocuments: [
      {
        title: 'Income Tax Act 2023 (Act No. 18 of 2023)',
        reference: 'ACT-18-2023',
        authority: 'National Board of Revenue (NBR)',
        url: 'https://nbr.gov.bd',
        date: 'June 2023',
      },
      {
        title: 'Finance Act 2024',
        reference: 'Act No. 12 of 2024',
        authority: 'Ministry of Finance & NBR',
        url: 'https://nbr.gov.bd',
        date: 'June 2024',
      },
      {
        title: 'NBR Paripatra 2024-2025 (Income Tax Clarification Manual)',
        reference: 'Paripatra 1 (Income Tax)',
        authority: 'NBR Tax Policy Wing',
        url: 'https://nbr.gov.bd',
        date: 'July 2024',
      },
    ],
  },

  '2025-2026': {
    assessmentYear: '2025-2026',
    incomeYear: '2024-2025',
    status: 'Upcoming / Provisional Planning Rules',
    act: 'Income Tax Act 2023 & Finance Act 2025 Projections',
    gazetteRef: 'Provisional Fiscal Framework',
    lastVerified: 'September 2024',
    generalThreshold: 350000,
    exemptionThresholds: [
      { id: 'general', category: 'General Individual (Male)', limit: 350000, formatted: '৳ 3,50,000', description: 'Provisional standard threshold' },
      { id: 'female', category: 'Female Taxpayers', limit: 400000, formatted: '৳ 4,00,000', description: 'Provisional threshold' },
      { id: 'seniorCitizen', category: 'Senior Citizens (Age 65+)', limit: 400000, formatted: '৳ 4,00,000', description: 'Provisional threshold' },
      { id: 'thirdGender', category: 'Third Gender Taxpayers', limit: 400000, formatted: '৳ 4,00,000', description: 'Provisional threshold' },
      { id: 'disabled', category: 'Persons with Disabilities', limit: 475000, formatted: '৳ 4,75,000', description: 'Provisional threshold' },
      { id: 'freedomFighter', category: 'Gazetted Freedom Fighters', limit: 500000, formatted: '৳ 5,00,000', description: 'Provisional threshold' },
      { id: 'parentOfDisabled', category: 'Parent/Guardian of Disabled Child', limit: 50000, formatted: '+ ৳ 50,000 / child', description: 'Additional allowance per disabled dependent child' },
    ],
    slabs: [
      { sequence: 1, range: 'First ৳ 3,50,000*', lowerLimit: 0, upperLimit: 350000, rate: 0, description: 'Tax-free exemption limit' },
      { sequence: 2, range: 'Next ৳ 1,00,000', lowerLimit: 350000, upperLimit: 450000, rate: 5, description: 'Lowest progressive taxable tier' },
      { sequence: 3, range: 'Next ৳ 4,00,000', lowerLimit: 450000, upperLimit: 850000, rate: 10, description: 'Middle bracket' },
      { sequence: 4, range: 'Next ৳ 5,00,000', lowerLimit: 850000, upperLimit: 1350000, rate: 15, description: 'Upper-middle bracket' },
      { sequence: 5, range: 'Next ৳ 5,00,000', lowerLimit: 1350000, upperLimit: 1850000, rate: 20, description: 'Higher bracket' },
      { sequence: 6, range: 'Remaining Balance', lowerLimit: 1850000, upperLimit: null, rate: 25, description: 'Top marginal progressive bracket' },
    ],
    minimumTaxes: [
      { id: 'dhaka_chattogram', area: 'Dhaka & Chattogram City Corporations', amount: 5000, formatted: '৳ 5,000', description: 'Statutory city corporation minimum' },
      { id: 'other_city_corporation', area: 'Other City Corporation Areas', amount: 4000, formatted: '৳ 4,000', description: 'Statutory divisional city minimum' },
      { id: 'non_city_corporation', area: 'Non-City / Municipalities / Rural Areas', amount: 3000, formatted: '৳ 3,000', description: 'Statutory rural minimum' },
    ],
    rebateRules: {
      section: 'Section 78, Income Tax Act 2023',
      rate: 15,
      rateFormatted: '15% of allowable investment',
      incomeCeilingPercentage: 20,
      incomeCeilingFormatted: '20% of net taxable income',
      maxStatutoryCap: 1000000,
      maxStatutoryCapFormatted: '৳ 10,00,000',
      dpsAnnualCap: 120000,
      dpsAnnualCapFormatted: '৳ 1,20,000 / year',
      allowableInstruments: ['DPS', 'Sanchayapatra', 'Life Insurance', 'Stock Market', 'Provident Fund', 'Benevolent Fund'],
    },
    surchargeRules: {
      section: 'Finance Act Statutory Framework',
      wealthThreshold: 40000000,
      wealthThresholdFormatted: '৳ 4 Crore',
      tiers: [
        { tier: 'Up to ৳ 4 Crore', rate: 0, description: 'No Surcharge' },
        { tier: 'Above ৳ 4 Crore to ৳ 10 Crore', rate: 10, description: '10% on calculated tax' },
        { tier: 'Above ৳ 10 Crore to ৳ 20 Crore', rate: 20, description: '20% on calculated tax' },
        { tier: 'Above ৳ 20 Crore to ৳ 50 Crore', rate: 30, description: '30% on calculated tax' },
        { tier: 'Exceeding ৳ 50 Crore', rate: 35, description: '35% on calculated tax' },
      ],
      assetTriggers: [
        { trigger: 'Owning more than 1 motor vehicle', rate: 10, description: '10% minimum surcharge' },
        { trigger: 'Owning residential property exceeding 8,000 sq ft', rate: 10, description: '10% minimum surcharge' },
      ],
    },
    salaryDeductions: {
      houseRent: 'Lower of actual received, 50% of basic salary, or ৳ 3,00,000/year',
      medical: 'Lower of actual received, 10% of basic salary, or ৳ 1,20,000/year',
      conveyance: 'Lower of actual received or ৳ 30,000/year',
    },
    officialDocuments: [
      {
        title: 'Income Tax Act 2023 & Planning Framework',
        reference: 'ACT-18-2023',
        authority: 'National Board of Revenue (NBR)',
        url: 'https://nbr.gov.bd',
        date: 'Provisional',
      },
    ],
  },

  '2023-2024': {
    assessmentYear: '2023-2024',
    incomeYear: '2022-2023',
    status: 'Historical (Initial Income Tax Act 2023 Implementation)',
    act: 'Income Tax Act 2023 & Finance Act 2023',
    gazetteRef: 'Bangladesh Gazette Extra Ordinary, June 2023',
    lastVerified: 'September 2024',
    generalThreshold: 350000,
    exemptionThresholds: [
      { id: 'general', category: 'General Individual (Male)', limit: 350000, formatted: '৳ 3,50,000', description: 'Raised from ৳3,00,000 under previous ordinance' },
      { id: 'female', category: 'Female Taxpayers', limit: 400000, formatted: '৳ 4,00,000', description: 'Raised from ৳3,50,000' },
      { id: 'seniorCitizen', category: 'Senior Citizens (Age 65+)', limit: 400000, formatted: '৳ 4,00,000', description: 'Raised from ৳3,50,000' },
      { id: 'thirdGender', category: 'Third Gender Taxpayers', limit: 400000, formatted: '৳ 4,00,000', description: 'Introduced ৳4,00,000 parity threshold' },
      { id: 'disabled', category: 'Persons with Disabilities', limit: 475000, formatted: '৳ 4,75,000', description: 'Raised from ৳4,50,000' },
      { id: 'freedomFighter', category: 'Gazetted Freedom Fighters', limit: 500000, formatted: '৳ 5,00,000', description: 'Raised from ৳4,75,000' },
      { id: 'parentOfDisabled', category: 'Parent/Guardian of Disabled Child', limit: 50000, formatted: '+ ৳ 50,000 / child', description: 'Additional dependent deduction per child' },
    ],
    slabs: [
      { sequence: 1, range: 'First ৳ 3,50,000*', lowerLimit: 0, upperLimit: 350000, rate: 0, description: 'Tax-free exemption limit' },
      { sequence: 2, range: 'Next ৳ 1,00,000', lowerLimit: 350000, upperLimit: 450000, rate: 5, description: '5% initial taxable bracket' },
      { sequence: 3, range: 'Next ৳ 3,00,000', lowerLimit: 450000, upperLimit: 750000, rate: 10, description: '10% middle bracket (was ৳3L in 2023)' },
      { sequence: 4, range: 'Next ৳ 4,00,000', lowerLimit: 750000, upperLimit: 1150000, rate: 15, description: '15% bracket' },
      { sequence: 5, range: 'Next ৳ 5,00,000', lowerLimit: 1150000, upperLimit: 1650000, rate: 20, description: '20% bracket' },
      { sequence: 6, range: 'Remaining Balance', lowerLimit: 1650000, upperLimit: null, rate: 25, description: '25% top bracket' },
    ],
    minimumTaxes: [
      { id: 'dhaka_chattogram', area: 'Dhaka & Chattogram City Corporations', amount: 5000, formatted: '৳ 5,000', description: 'Statutory city corporation minimum' },
      { id: 'other_city_corporation', area: 'Other City Corporation Areas', amount: 4000, formatted: '৳ 4,000', description: 'Statutory divisional city minimum' },
      { id: 'non_city_corporation', area: 'Non-City / Municipalities / Rural Areas', amount: 3000, formatted: '৳ 3,000', description: 'Statutory rural minimum' },
    ],
    rebateRules: {
      section: 'Section 78, Income Tax Act 2023',
      rate: 15,
      rateFormatted: '15% flat rate',
      incomeCeilingPercentage: 20,
      incomeCeilingFormatted: '20% of taxable income',
      maxStatutoryCap: 1000000,
      maxStatutoryCapFormatted: '৳ 10,00,000',
      dpsAnnualCap: 120000,
      dpsAnnualCapFormatted: '৳ 1,20,000 / year',
      allowableInstruments: ['DPS', 'Sanchayapatra', 'Life Insurance', 'Stock Market', 'Provident Fund'],
    },
    surchargeRules: {
      section: 'Finance Act 2023',
      wealthThreshold: 40000000,
      wealthThresholdFormatted: '৳ 4 Crore',
      tiers: [
        { tier: 'Up to ৳ 4 Crore', rate: 0, description: 'No Surcharge' },
        { tier: 'Above ৳ 4 Crore to ৳ 10 Crore', rate: 10, description: '10% on calculated tax' },
        { tier: 'Above ৳ 10 Crore to ৳ 20 Crore', rate: 20, description: '20% on calculated tax' },
        { tier: 'Above ৳ 20 Crore to ৳ 50 Crore', rate: 30, description: '30% on calculated tax' },
        { tier: 'Exceeding ৳ 50 Crore', rate: 35, description: '35% on calculated tax' },
      ],
      assetTriggers: [
        { trigger: 'Owning more than 1 motor vehicle', rate: 10, description: '10% minimum surcharge' },
      ],
    },
    salaryDeductions: {
      houseRent: 'Lower of actual received, 50% of basic salary, or ৳ 3,00,000/year',
      medical: 'Lower of actual received, 10% of basic salary, or ৳ 1,20,000/year',
      conveyance: 'Lower of actual received or ৳ 30,000/year',
    },
    officialDocuments: [
      {
        title: 'Income Tax Act 2023 (Act No. 18 of 2023)',
        reference: 'ACT-18-2023',
        authority: 'National Board of Revenue (NBR)',
        url: 'https://nbr.gov.bd',
        date: 'June 2023',
      },
    ],
  },
};

export const WHATS_CHANGED_TIMELINE = [
  {
    id: 'change-1',
    topic: 'Tax-Free Exemption Thresholds',
    title: 'Increase in Base Tax-Free Threshold from ৳3.0 Lakh to ৳3.5 Lakh',
    effectiveAY: '2023-2024 onwards',
    oldRule: 'General Individual threshold was ৳ 3,00,000 (Female/Senior: ৳ 3,50,000) under the Income Tax Ordinance 1984.',
    newRule: 'General Individual threshold increased to ৳ 3,50,000 (Female/Senior/Third Gender: ৳ 4,00,000, Disabled: ৳ 4,75,000, Freedom Fighters: ৳ 5,00,000).',
    officialSource: 'Income Tax Act 2023 & Finance Act 2023 First Schedule',
    authority: 'National Board of Revenue (NBR)',
    impact: 'Reduces tax burden by saving up to ৳2,500 for entry-level taxpayers.',
    badge: 'Threshold Change',
    badgeColor: 'emerald',
  },
  {
    id: 'change-2',
    topic: 'Tax Slabs & Tier Widths',
    title: 'Expansion of Middle Tax Slabs in Finance Act 2024',
    effectiveAY: '2024-2025',
    oldRule: '10% slab was applied to the next ৳ 3,00,000; 15% slab was applied to the next ৳ 4,00,000.',
    newRule: '10% slab expanded to next ৳ 4,00,000; 15% slab expanded to next ৳ 5,00,000; 20% slab expanded to next ৳ 5,00,000.',
    officialSource: 'Finance Act 2024, Section 2 & NBR Paripatra 2024-2025',
    authority: 'National Board of Revenue (NBR)',
    impact: 'Taxpayers earning between ৳8.5L and ৳18.5L pay lower marginal tax on expanded brackets.',
    badge: 'Slab Modification',
    badgeColor: 'blue',
  },
  {
    id: 'change-3',
    topic: 'Section 78 Investment Rebates',
    title: 'Simplified Single 15% Rebate Rate with 20% Taxable Income Cap',
    effectiveAY: '2023-2024 onwards',
    oldRule: 'Multi-tiered rebate system (15% for income < ৳15L; 10% for income > ৳15L, capped at 25% of taxable income).',
    newRule: 'Unified flat 15% rebate rate on allowable investments, capped at the lower of actual investment, 20% of taxable income, or ৳ 10,00,000 max cap.',
    officialSource: 'Section 78 & Schedule 6 Part 3, Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
    impact: 'Clearer, predictable rebate calculations across all income brackets.',
    badge: 'Rebate Reform',
    badgeColor: 'amber',
  },
  {
    id: 'change-4',
    topic: 'Net Wealth Surcharge',
    title: 'Surcharge Exemption Ceiling Raised to ৳4 Crore with Specific Asset Triggers',
    effectiveAY: '2023-2024 onwards',
    oldRule: 'Surcharge applied starting at ৳ 3 Crore net wealth.',
    newRule: 'Surcharge threshold raised to ৳ 4 Crore. However, owning 2+ motor vehicles or 8,000+ sq ft property triggers minimum 10% surcharge regardless of wealth amount.',
    officialSource: 'Finance Act 2023 / Finance Act 2024 Section 4',
    authority: 'National Board of Revenue (NBR)',
    impact: 'Exempts middle-class wealth holders while targeting high-value physical luxury assets.',
    badge: 'Surcharge Restructure',
    badgeColor: 'purple',
  },
  {
    id: 'change-5',
    topic: 'Mandatory Proof of Return (PSR)',
    title: 'Expansion to 43+ Statutory Services for Mandatory Return Submission',
    effectiveAY: '2023-2024 onwards',
    oldRule: 'TIN certificate was sufficient for banking, utility connections, and property registration.',
    newRule: 'Proof of Submission of Return (PSR / Acknowledgment Receipt) is strictly mandatory for 43+ services under Section 264.',
    officialSource: 'Section 264, Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
    impact: 'Enforces filing compliance for credit cards, trade licenses, land transfers, and corporate executives.',
    badge: 'Compliance Rule',
    badgeColor: 'slate',
  },
];
