/**
 * TaxBD Comprehensive Tax Education Hub Data
 * Explains Bangladesh Income Tax in plain, beginner-friendly language with full bilingual support.
 */

export const GUIDE_CATEGORIES = [
  {
    id: 'income-tax-basics',
    title: 'Income Tax Basics',
    titleBn: 'আয়করের মৌলিক বিষয়',
    description: 'Fundamental principles of taxation in Bangladesh, who must pay, and basic terms.',
    descriptionBn: 'বাংলাদেশে আয়করের প্রাথমিক নীতিমালা, কাদের কর দিতে হয় এবং মৌলিক পরিভাষা।',
    icon: 'BookOpen',
    color: 'emerald',
    count: 2,
  },
  {
    id: 'taxable-income',
    title: 'Taxable Income',
    titleBn: 'করযোগ্য আয়',
    description: 'How your gross salary and business revenue are converted into your net tax base.',
    descriptionBn: 'কীভাবে আপনার মোট বেতন ও ব্যবসায়ের আয় থেকে নিট করযোগ্য আয় হিসাব করা হয়।',
    icon: 'Calculator',
    color: 'blue',
    count: 1,
  },
  {
    id: 'tax-free-income',
    title: 'Tax-Free Income',
    titleBn: 'করমুক্ত আয় ও সুবিধাসমূহ',
    description: 'Statutory allowances, thresholds, and income categories that are 100% tax-exempt.',
    descriptionBn: 'আইনগত ভাতা, করমুক্ত প্রারম্ভিক সীমা এবং শতভাগ করমুক্ত আয়ের খাতসমূহ।',
    icon: 'ShieldCheck',
    color: 'teal',
    count: 1,
  },
  {
    id: 'tax-slabs',
    title: 'Tax Slabs',
    titleBn: 'প্রগতিশীল কর ধাপ',
    description: 'How the 0%, 5%, 10%, 15%, 20%, and 25% progressive tax tiers work without guesswork.',
    descriptionBn: '০%, ৫%, ১০%, ১৫%, ২০% এবং ২৫% প্রগতিশীল কর ধাপের সঠিক কার্যপদ্ধতি।',
    icon: 'Layers',
    color: 'purple',
    count: 1,
  },
  {
    id: 'tax-rebates',
    title: 'Tax Rebates',
    titleBn: 'বিনিয়োগ কর রেয়াত',
    description: 'Section 78 investment tax credits: DPS, Sanchayapatra, stocks, and insurance.',
    descriptionBn: 'ধারা ৭৮ অনুযায়ী ডিপিএস, সঞ্চয়পত্র, শেয়ার ও জীবন বীমায় সর্বোচ্চ ১৫% কর রেয়াত।',
    icon: 'TrendingUp',
    color: 'amber',
    count: 1,
  },
  {
    id: 'minimum-tax',
    title: 'Minimum Tax',
    titleBn: 'ন্যূনতম কর',
    description: 'Geographic minimum tax requirements across Dhaka, Chattogram, and regional areas.',
    descriptionBn: 'ঢাকা, চট্টগ্রাম ও অন্যান্য অঞ্চলের জন্য নির্ধারিত ন্যূনতম করের বাধ্যবাধকতা।',
    icon: 'MapPin',
    color: 'indigo',
    count: 1,
  },
  {
    id: 'surcharge',
    title: 'Surcharge',
    titleBn: 'সম্পদ সারচার্জ',
    description: 'Net wealth surcharge rules for high net-worth individuals and multiple vehicle owners.',
    descriptionBn: '৪ কোটি টাকার বেশি সম্পদ বা একাধিক মোটরগাড়ির মালিকদের জন্য প্রযোজ্য সারচার্জ।',
    icon: 'Coins',
    color: 'orange',
    count: 1,
  },
  {
    id: 'tax-return',
    title: 'Tax Return',
    titleBn: 'আয়কর রিটার্ন দাখিল',
    description: 'Annual return submission deadlines, mandatory filing conditions, and penalty rules.',
    descriptionBn: 'বার্ষিক রিটার্ন দাখিলের সময়সীমা, বাধ্যতামূলক দাখিলের শর্ত এবং জরিমানা সংক্রান্ত বিধিমালা।',
    icon: 'FileText',
    color: 'slate',
    count: 1,
  },
  {
    id: 'e-return',
    title: 'e-Return',
    titleBn: 'অনলাইন ই-রিটার্ন',
    description: 'Step-by-step guidance on filing your return online through etaxnbr.gov.bd.',
    descriptionBn: 'etaxnbr.gov.bd পোর্টালের মাধ্যমে অনলাইনে সহজে ই-রিটার্ন দাখিলের পূর্ণাঙ্গ নির্দেশিকা।',
    icon: 'Laptop',
    color: 'emerald',
    count: 1,
  },
  {
    id: 'taxpayer-categories',
    title: 'Taxpayer Categories',
    titleBn: 'করদাতার শ্রেণি ও বিশেষ সুবিধা',
    description: 'Special tax-free exemption limits for women, seniors, freedom fighters, and disabled persons.',
    descriptionBn: 'নারী, প্রবীণ, মুক্তিযোদ্ধা এবং প্রতিবন্ধী করদাতাদের জন্য বিশেষ করমুক্ত সীমা।',
    icon: 'Users',
    color: 'blue',
    count: 1,
  },
];

export const GUIDE_ARTICLES = [
  // 1. Income Tax Basics - Article 1
  {
    slug: 'what-is-income-tax-bangladesh',
    categoryId: 'income-tax-basics',
    title: 'What is Income Tax in Bangladesh?',
    titleBn: 'বাংলাদেশে আয়কর কী এবং কেন দিতে হয়?',
    shortExplanation: 'A mandatory financial contribution paid to the government on the annual income you earn.',
    shortExplanationBn: 'একটি অর্থবছরে অর্জিত মোট করযোগ্য আয়ের ওপর সরকারের অনুকূলে প্রদেয় সংবিধিবদ্ধ কর।',
    whoItAppliesTo: 'Any Bangladeshi resident or non-resident earning income inside Bangladesh above the statutory tax-free threshold.',
    whoItAppliesToBn: 'বাংলাদেশে বসবাসকারী বা অনাবাসী যেকোনো ব্যক্তি যার বার্ষিক আয় নির্ধারিত করমুক্ত সীমা অতিক্রম করে।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'Why do I have to pay income tax and how does it work?',
    simpleQuestionBn: 'আয়কর কেন দিতে হয় এবং এটি কীভাবে কাজ করে?',
    simpleAnswer:
      'Income tax is money paid to the government based on what you earn in a financial year (1 July to 30 June). The government uses this revenue to build infrastructure, hospitals, bridges, and public services. You only pay tax if your annual income exceeds the tax-free exemption threshold (e.g. ৳3,50,000 for male individuals, ৳4,00,000 for women).',
    simpleAnswerBn:
      'আয়কর হলো একটি অর্থবছরে (১ জুলাই – ৩০ জুন) আপনার উপার্জিত আয়ের ওপর নির্ধারিত সরকারি কর। জাতীয় রাজস্ব বোর্ড (NBR) এই রাজস্ব দিয়ে রাস্তাঘাট, হাসপাতাল, ব্রিজ ও নাগরিক সেবা নিশ্চিত করে। আপনার বার্ষিক আয় করমুক্ত সীমা (পুরুষদের জন্য ৩.৫ লাখ টাকা, নারীদের জন্য ৪.০ লাখ টাকা) অতিক্রম করলেই কেবল কর দিতে হয়।',
    visualExample: {
      title: 'Example: Earning ৳4,00,000 in a year',
      titleBn: 'বাস্তব উদাহরণ: বছরে ৪,০০,০০০ টাকা আয় হলে',
      steps: [
        'Total income earned in year: ৳4,00,000',
        'Tax-free threshold (Male): ৳3,50,000 (Tax = ৳0)',
        'Taxable portion: ৳50,000 taxed at 5% = ৳2,500',
        'Minimum tax adjustment (Dhaka): Raised to ৳5,000 statutory minimum',
      ],
      stepsBn: [
        'বছরে মোট অর্জিত আয়: ৪,০০,০০০ টাকা',
        'সাধারণ পুরুষ করমুক্ত সীমা: ৩,৫০,০০০ টাকা (কর = ০ টাকা)',
        'করযোগ্য অতিরিক্ত আয়: ৫০,০০০ টাকার ওপর ৫% হারে কর = ২,৫০০ টাকা',
        'ঢাকা সিটি কর্পোরেশন এলাকা অনুসারে ন্যূনতম কর সমন্বয়: ৫,০০০ টাকা',
      ],
      conclusion: 'You only pay tax on the portion above ৳3,50,000, subject to geographic minimum tax rules.',
      conclusionBn: 'আপনি কেবল ৩.৫০ লাখ টাকার অতিরিক্ত অংশের ওপর কর প্রদান করবেন এবং ভৌগোলিক ন্যূনতম কর প্রযোজ্য হবে।',
    },
    commonMistakes: [
      'Believing you must pay tax on your entire salary rather than just the taxable portion above the threshold.',
      'Assuming that having an e-TIN automatically requires paying tax, even when your earnings are below the exemption limit.',
      'Confusing the Income Year (when you earn) with the Assessment Year (when you file).',
    ],
    commonMistakesBn: [
      'সম্পূর্ণ বেতনের ওপর কর দিতে হবে মনে করা (প্রকৃতপক্ষে শুধু করমুক্ত সীমার অতিরিক্ত অংশের ওপর কর ধার্য হয়)।',
      'ই-টিআইএন থাকলেই কর দিতে হবে মনে করা (আয় করমুক্ত সীমার নিচে থাকলে প্রদেয় কর শূন্য)।',
      'আয়বর্ষ (যে বছর আয় করেছেন) এবং করবর্ষ (যে বছর রিটার্ন জমা দিচ্ছেন) এর মধ্যে বিভ্রান্ত হওয়া।',
    ],
    officialSource: {
      title: 'Income Tax Act 2023 (Act No. 18 of 2023)',
      actSection: 'Section 2(36) and Section 3',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2023 (Gazetted)',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 1. Income Tax Basics - Article 2
  {
    slug: 'income-year-vs-assessment-year',
    categoryId: 'income-tax-basics',
    title: 'Income Year vs. Assessment Year Explained',
    titleBn: 'আয়বর্ষ ও করবর্ষের পার্থক্য সহজ ভাষায়',
    shortExplanation: 'The Income Year is when you earn money; the Assessment Year is when you calculate and pay tax on it.',
    shortExplanationBn: 'আয়বর্ষ হলো যে অর্থবছরে আপনি টাকা উপার্জন করেন; করবর্ষ হলো তার পরবর্তী বছর যখন কর হিসাব ও দাখিল করা হয়।',
    whoItAppliesTo: 'All individual taxpayers preparing their annual tax returns.',
    whoItAppliesToBn: 'সকল ব্যক্তিগত করদাতা যারা বার্ষিক আয়কর রিটার্ন প্রস্তুত করেন।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'What is the difference between an Income Year and an Assessment Year?',
    simpleQuestionBn: 'আয়বর্ষ এবং করবর্ষের মধ্যে মূল পার্থক্য কী?',
    simpleAnswer:
      'In Bangladesh, tax is always assessed in the year following the year you earned the money. The 12 months in which you earn is your "Income Year" (1 July to 30 June). The next 12 months in which you file your return is your "Assessment Year".',
    simpleAnswerBn:
      'বাংলাদেশে যে অর্থবছরে আয় অর্জিত হয়, তার পরবর্তী অর্থবছরে কর নির্ধারণ ও পরিশোধ করা হয়। ১ জুলাই থেকে ৩০ জুন পর্যন্ত ১২ মাস হলো আপনার "আয়বর্ষ"। আর পরবর্তী অর্থবছরে রিটার্ন দাখিলের সময়কাল হলো "করবর্ষ"।',
    visualExample: {
      title: 'Timeline of AY 2024–2025',
      titleBn: 'করবর্ষ ২০২৪-২০২৫ এর সময়রেখা',
      steps: [
        '1 July 2023 – 30 June 2024: You earn salary, rent, or business revenue (Income Year 2023–2024)',
        '1 July 2024 – 30 June 2025: You file return and pay tax (Assessment Year 2024–2025)',
        '30 November 2024: Official National Tax Day submission deadline',
      ],
      stepsBn: [
        '১ জুলাই ২০২৩ – ৩০ জুন ২০২৪: আপনি বেতন, ব্যবসা বা ভাড়া থেকে আয় করেন (আয়বর্ষ ২০২৩–২৪)',
        '১ জুলাই ২০২৪ – ৩০ জুন ২০২৫: আপনি রিটার্ন দাখিল ও কর সমন্বয় করেন (করবর্ষ ২০২৪–২৫)',
        '৩০ নভেম্বর ২০২৪: জাতীয় কর দিবস (রিটার্ন দাখিলের নির্ধারিত শেষ দিন)',
      ],
      conclusion: 'Your 2024 tax calculation evaluates earnings from July 2023 through June 2024.',
      conclusionBn: 'আপনার ২০২৪-২৫ করবর্ষের হিসাব জুলাই ২০২৩ থেকে জুন ২০২৪ পর্যন্ত উপার্জনের ওপর প্রযোজ্য।',
    },
    commonMistakes: [
      'Using the current month salary instead of total income from the preceding fiscal year (1 July to 30 June).',
      'Thinking Assessment Year 2024-2025 means earnings made between July 2024 and June 2025.',
    ],
    commonMistakesBn: [
      'বিগত সমাপ্ত অর্থবছরের মোট আয়ের বদলে চলতি মাসের আয়ের ভিত্তিতে রিটার্ন হিসাব করা।',
      'করবর্ষ ২০২৪-২০২৫ বলতে ২০২৪ এর জুলাই থেকে ২০২৫ এর জুন পর্যন্ত আয় মনে করা।',
    ],
    officialSource: {
      title: 'Income Tax Act 2023',
      actSection: 'Section 2(9) and Section 2(10)',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2023',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 2. Taxable Income
  {
    slug: 'how-to-calculate-taxable-income',
    categoryId: 'taxable-income',
    title: 'How Taxable Income is Calculated from Gross Salary',
    titleBn: 'মোট বেতন থেকে করযোগ্য আয় যেভাবে হিসাব করবেন',
    shortExplanation: 'Taxable income is what remains after subtracting statutory salary allowances (house rent, medical, conveyance).',
    shortExplanationBn: 'মোট বেতন থেকে বাড়িভাড়া, চিকিৎসা ও যাতায়াত ভাতার আইনগত করমুক্ত অংশ বাদ দিয়ে করযোগ্য আয় নির্ণয় করা হয়।',
    whoItAppliesTo: 'Salaried employees in private companies, MNCs, banks, and government organizations.',
    whoItAppliesToBn: 'সরকারি, আধা-সরকারি, ব্যাংক, বহুজাতিক ও বেসরকারি প্রতিষ্ঠানের সকল বেতনভোগী কর্মকর্তা-কর্মচারী।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'Why is my taxable income lower than my gross salary on my payslip?',
    simpleQuestionBn: 'পে-স্লিপের মোট বেতনের চেয়ে করযোগ্য আয়ের পরিমাণ কম হয় কেন?',
    simpleAnswer:
      'The law gives statutory exemptions on specific employment allowances. Portions of your house rent, medical allowance, and conveyance allowance are exempt from tax up to official caps. You only pay tax on the remaining balance.',
    simpleAnswerBn:
      'আয়কর আইন অনুযায়ী নির্দিষ্ট কিছু ভাতায় কর ছাড় দেওয়া হয়েছে। বাড়িভাড়া ভাতা, চিকিৎসা ভাতা ও যাতায়াত ভাতার একটি অংশ নির্ধারিত সীমা পর্যন্ত সম্পূর্ণ করমুক্ত। অবশিষ্ট অংশের ওপর কর ধার্য হওয়ায় করযোগ্য আয় মোট বেতনের চেয়ে কম হয়।',
    visualExample: {
      title: 'Case Study: Annual Salary of ৳10,36,000',
      titleBn: 'বাস্তব উদাহরণ: বার্ষিক মোট বেতন ১০,৩৬,০০০ টাকা',
      steps: [
        'Basic Salary: ৳6,00,000 (Fully taxable)',
        'House Rent Allowance: ৳2,40,000 → Exemption: Min(2.4L, 50% basic=3.0L, 3.0L) = ৳2,40,000 (৳0 taxable)',
        'Medical Allowance: ৳60,000 → Exemption: Min(60k, 10% basic=60k, 1.2L) = ৳60,000 (৳0 taxable)',
        'Conveyance Allowance: ৳36,000 → Exemption: ৳30,000 (৳6,000 taxable)',
        'Festival Bonus: ৳1,00,000 (Fully taxable)',
        'Total Gross: ৳10,36,000 | Total Exemptions: ৳3,30,000',
        'Net Taxable Income = ৳10,36,000 − ৳3,30,000 = ৳7,06,000',
      ],
      stepsBn: [
        'মূল বেতন: ৬,০০,০০০ টাকা (শতভাগ করযোগ্য)',
        'বাড়িভাড়া ভাতা: ২,৪০,০০০ টাকা → করমুক্ত সীমা: ২,৪০,০০০ টাকা (০ টাকা করযোগ্য)',
        'চিকিৎসা ভাতা: ৬০,০০০ টাকা → করমুক্ত সীমা: ৬০,০০০ টাকা (০ টাকা করযোগ্য)',
        'যাতায়াত ভাতা: ৩৬,০০০ টাকা → করমুক্ত সীমা: ৩০,০০০ টাকা (৬,০০০ টাকা করযোগ্য)',
        'উৎসব বোনাস: ১,০০,০০০ টাকা (শতভাগ করযোগ্য)',
        'মোট আয়: ১০,৩৬,০০০ টাকা | মোট অনুমোদনযোগ্য ছাড়: ৩,৩০,০০০ টাকা',
        'নিট করযোগ্য আয় = ১০,৩৬,০০০ − ৩,৩০,০০০ = ৭,০৬,০০০ টাকা',
      ],
      conclusion: 'You only pay tax on ৳7,06,000 instead of ৳10,36,000, saving thousands of Taka.',
      conclusionBn: 'আপনি ১০.৩৬ লাখের বদলে মাত্র ৭.০৬ লাখ টাকার ওপর কর দেবেন, যা আপনার হাজার হাজার টাকা সাশ্রয় করবে।',
    },
    commonMistakes: [
      'Applying tax to gross salary without deducting house rent, medical, and conveyance exemptions.',
      'Claiming medical exemption above ৳1,20,000 or 10% of basic salary.',
    ],
    commonMistakesBn: [
      'ভাতার আইনগত ছাড় বাদ না দিয়েই সম্পূর্ণ মোট বেতনের ওপর কর হিসাব করা।',
      'চিকিৎসা ভাতার ক্ষেত্রে সর্বোচ্চ ১,২০,০০০ টাকা বা মূল বেতনের ১০% এর অতিরিক্ত ছাড় দাবি করা।',
    ],
    officialSource: {
      title: 'Sixth Schedule, Part 1, Income Tax Act 2023',
      actSection: 'Section 38 & Sixth Schedule Part 1',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2023',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 3. Tax-Free Income
  {
    slug: 'tax-free-allowances-and-exemptions',
    categoryId: 'tax-free-income',
    title: 'Official Tax-Free Allowances and Statutory Exemptions',
    titleBn: 'আইনগত করমুক্ত আয়ের খাত ও অনুমোদনযোগ্য সুবিধাসমূহ',
    shortExplanation: 'Complete list of income heads and components that do not incur any income tax in Bangladesh.',
    shortExplanationBn: 'বাংলাদেশে যেসব আয়ের ওপর কোনো কর দিতে হয় না তার পূর্ণাঙ্গ তালিকা ও আইনি ব্যাখ্যা।',
    whoItAppliesTo: 'Salaried individuals, farmers, pensioners, and recipients of government allowances.',
    whoItAppliesToBn: 'বেতনভোগী, পেনশনভোগী, ক্ষুদ্র কৃষক এবং সরকারি ভাতা গ্রহণকারী ব্যক্তিবর্গ।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'What kinds of income are completely tax-free in Bangladesh?',
    simpleQuestionBn: 'বাংলাদেশে কোন কোন আয়ের ওপর সম্পূর্ণ কর ছাড় পাওয়া যায়?',
    simpleAnswer:
      'Certain incomes are protected from tax by law. Examples include pension payments, gratuity funds up to statutory limits, government awards, agricultural income up to ৳2,00,000 for sole farmers, and specific salary allowance exemptions.',
    simpleAnswerBn:
      'আইন অনুসারে বেশ কিছু আয় সম্পূর্ণ করমুক্ত। যেমন: পেনশন, নির্দিষ্ট সীমা পর্যন্ত গ্র্যাচুইটি, জাতীয় পদক ও পুরস্কারের অর্থ, ক্ষুদ্র কৃষকদের ২ লাখ টাকা পর্যন্ত কৃষি আয় এবং বেতনের বাড়িভাড়া ও চিকিৎসা ভাতার নির্দিষ্ট অংশ।',
    visualExample: {
      title: 'Common Tax-Free Allowances',
      titleBn: 'প্রধান করমুক্ত সুবিধাসমূহ',
      steps: [
        'House rent exemption: Lower of actual received, 50% of basic, or ৳3,00,000/year',
        'Medical allowance: Lower of actual received, 10% of basic, or ৳1,20,000/year',
        'Conveyance allowance: Up to ৳30,000 per year',
        'Pension & Gratuity: Fully tax-free for recognized funds',
      ],
      stepsBn: [
        'বাড়িভাড়া ছাড়: প্রাপ্ত ভাতা, মূল বেতনের ৫০% বা বার্ষিক ৩ লাখ টাকার মধ্যে যেটি কম',
        'চিকিৎসা ভাতা ছাড়: প্রাপ্ত ভাতা, মূল বেতনের ১০% বা বার্ষিক ১.২ লাখ টাকার মধ্যে যেটি কম',
        'যাতায়াত ভাতা ছাড়: বার্ষিক সর্বোচ্চ ৩০,০০০ টাকা পর্যন্ত',
        'পেনশন ও গ্র্যাচুইটি: অনুমোদিত তহবিলের ক্ষেত্রে শতভাগ করমুক্ত',
      ],
      conclusion: 'These amounts are deducted before progressive slabs are calculated.',
      conclusionBn: 'প্রগতিশীল কর ধাপ প্রয়োগের পূর্বেই এই করমুক্ত অর্থ মোট আয় থেকে বিয়োগ করা হয়।',
    },
    commonMistakes: [
      'Assuming all cash allowances are 100% tax-free without verifying statutory ceilings.',
    ],
    commonMistakesBn: [
      'আইনগত সর্বোচ্চ সীমা যাচাই না করেই সমস্ত নগদ ভাতাকে শতভাগ করমুক্ত মনে করা।',
    ],
    officialSource: {
      title: 'Income Tax Act 2023 Sixth Schedule',
      actSection: 'Part 1, Sixth Schedule',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2023',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 4. Tax Slabs
  {
    slug: 'what-is-a-tax-slab-progressive-rates',
    categoryId: 'tax-slabs',
    title: 'What is a Tax Slab? How Progressive Tax Rates Work',
    titleBn: 'কর ধাপ (Tax Slab) কী? প্রগতিশীল করের হার যেভাবে কাজ করে',
    shortExplanation: 'Bangladesh uses progressive tax tiers where different portions of your income are taxed at increasing rates.',
    shortExplanationBn: 'বাংলাদেশে আয়ের বিভিন্ন স্তরের ওপর ০%, ৫%, ১০%, ১৫%, ২০% এবং ২৫% হারে প্রগতিশীল কর ধার্য হয়।',
    whoItAppliesTo: 'All individual taxpayers with taxable income exceeding ৳3,50,000.',
    whoItAppliesToBn: 'সকল করদাতা যাদের বার্ষিক করযোগ্য আয় ৩,৫০,০০০ টাকার বেশি।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'What is a tax slab and why don’t I pay one single percentage on all my money?',
    simpleQuestionBn: 'কর ধাপ কী এবং সম্পূর্ণ আয়ের ওপর একবারে কর ধার্য হয় না কেন?',
    simpleAnswer:
      'Bangladesh uses progressive tax rates. This means different portions of your taxable income are taxed at different rates (0%, 5%, 10%, 15%, 20%, 25%). If your income increases and crosses into a higher slab, only the extra portion is taxed at the higher rate—never your whole income.',
    simpleAnswerBn:
      'বাংলাদেশে প্রগতিশীল কর ব্যবস্থা অনুসৃত হয়। আপনার আয় বেড়ে পরবর্তী ধাপে প্রবেশ করলে শুধু সেই বাড়তি অংশের ওপরই উচ্চতর হার প্রযোজ্য হবে, কখনোই সম্পূর্ণ আয়ের ওপর নয়। ফলে আয় বাড়লে করের হার বাড়ে কেবল অতিরিক্ত অংশের ওপর।',
    visualExample: {
      title: 'Visual Slab Breakdown for ৳8,50,000 Taxable Income (Male)',
      titleBn: '৮,৫০,০০০ টাকা করযোগ্য আয়ের ধাপভিত্তিক বিশ্লেষণ (পুরুষ)',
      steps: [
        '1st ৳3,50,000 (Tax-Free Threshold) @ 0% = ৳0',
        'Next ৳1,00,000 @ 5% = ৳5,000',
        'Next ৳4,00,000 @ 10% = ৳40,000',
        'Total Regular Tax = ৳5,00,0 + ৳40,000 = ৳45,000',
      ],
      stepsBn: [
        'প্রথম ৩,৫০,০০০ টাকা (করমুক্ত সীমা) @ ০% = ০ টাকা',
        'পরবর্তী ১,০০,০০০ টাকা @ ৫% = ৫,০০০ টাকা',
        'পরবর্তী ৪,০০,০০০ টাকা @ ১০% = ৪০,০০০ টাকা',
        'মোট প্রাথমিক কর = ৫,০০০ + ৪০,০০০ = ৪৫,০০০ টাকা',
      ],
      conclusion: 'Effective tax rate is only 5.29% of your total income, not 10% on everything.',
      conclusionBn: 'আপনার কার্যকর করের হার হবে মোট আয়ের মাত্র ৫.২৯%, পুরো ৮.৫ লাখের ওপর ১০% নয়।',
    },
    commonMistakes: [
      'Fearing a salary raise because you think crossing a slab will cause your entire income to be taxed at the higher rate.',
      'Applying 25% to your full income when only the portion exceeding ৳18.5 Lakh is taxed at 25%.',
    ],
    commonMistakesBn: [
      'পরবর্তী ধাপে প্রবেশ করলে পুরো আয়ের ওপরই উচ্চ হারের কর কাটা যাবে এই অমূলক ভয় পাওয়া।',
      '১৮.৫ লাখের অতিরিক্ত অংশের বদলে পুরো আয়ের ওপর সর্বোচ্চ ২৫% হার হিসাব করা।',
    ],
    officialSource: {
      title: 'Finance Act 2024 & Income Tax Act 2023',
      actSection: 'First Schedule / Paripatra 2024-2025',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2024',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 5. Tax Rebates
  {
    slug: 'section-78-investment-rebate-guide',
    categoryId: 'tax-rebates',
    title: 'Section 78 Investment Rebates: How to Save 15% on Tax',
    titleBn: 'ধারা ৭৮: অনুমোদিত খাতে বিনিয়োগ করে ১৫% কর রেয়াত যেভাবে পাবেন',
    shortExplanation: 'Invest in approved savings schemes to directly cut your tax liability by 15% of allowable investments.',
    shortExplanationBn: 'ডিপিএস, সঞ্চয়পত্র, শেয়ারবাজার ও জীবন বীমায় বিনিয়োগ করে প্রদেয় কর থেকে সরাসরি ১৫% রেয়াত পান।',
    whoItAppliesTo: 'Taxpayers who invest in DPS, Sanchayapatra, life insurance, stock market, or provident funds.',
    whoItAppliesToBn: 'ডিপিএস, সঞ্চয়পত্র, জীবন বীমা, প্রভিডেন্ট ফান্ড ও শেয়ারবাজারে বিনিয়োগকারী ব্যক্তিবর্গ।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'How can I legally reduce my income tax through investments?',
    simpleQuestionBn: 'বিনিয়োগের মাধ্যমে কীভাবে আইনসম্মতভাবে করের পরিমাণ কমানো যায়?',
    simpleAnswer:
      'Under Section 78 of the Income Tax Act 2023, you receive a 15% tax rebate on eligible investments. The allowable investment is capped at the lowest of: (1) Your actual investments, (2) 20% of your taxable income, or (3) ৳10,00,000.',
    simpleAnswerBn:
      'আয়কর আইন ২০২৩-এর ৭৮ ধারা অনুযায়ী অনুমোদিত খাতে বিনিয়োগের ওপর ১৫% কর রেয়াত পাওয়া যায়। অনুমোদনযোগ্য বিনিয়োগ সীমা হলো তিনটি রাশির মধ্যে যেটি কম: (১) প্রকৃত বিনিয়োগ, (২) করযোগ্য আয়ের ২০%, অথবা (৩) ১০,০০,০০০ টাকা।',
    visualExample: {
      title: 'Example: Taxable Income ৳10,00,000 with ৳1,50,000 in DPS & Life Insurance',
      titleBn: 'বাস্তব উদাহরণ: ১০ লাখ টাকা করযোগ্য আয়ে ১.৫ লাখ টাকা বিনিয়োগ থাকলে',
      steps: [
        'Taxable Income: ৳10,00,000',
        '20% Income Ceiling: ৳2,00,000',
        'Actual Investments: ৳1,50,000 (Allowable since ৳1.5L < ৳2.0L and < ৳10L)',
        'Section 78 Rebate = ৳1,50,000 × 15% = ৳22,500',
        'If regular tax was ৳65,000 → Net Tax = ৳65,000 − ৳22,500 = ৳42,500',
      ],
      stepsBn: [
        'করযোগ্য আয়: ১০,০০,০০০ টাকা',
        '২০% আয়ের সর্বোচ্চ সীমা: ২,০০,০০০ টাকা',
        'প্রকৃত বিনিয়োগ: ১,৫০,০০০ টাকা (অনুমোদনযোগ্য কারণ ১.৫ লাখ < ২ লাখ এবং < ১০ লাখ)',
        'ধারা ৭৮ রেয়াত = ১,৫০,০০০ × ১৫% = ২২,৫০০ টাকা',
        'প্রাথমিক কর ৬৫,০০০ টাকা হলে → নিট প্রদেয় কর = ৬৫,০০০ − ২২,৫০০ = ৪২,৫০০ টাকা',
      ],
      conclusion: 'You save ৳22,500 directly from your tax bill by investing in approved schemes.',
      conclusionBn: 'অনুমোদিত খাতে বিনিয়োগ করে আপনি সরাসরি ২২,৫০০ টাকা কর সাশ্রয় করতে পারছেন।',
    },
    commonMistakes: [
      'Investing more than ৳1,20,000/year in DPS expecting full rebate (DPS rebate is capped at ৳1.2L annually).',
      'Assuming investment rebate can reduce tax below the mandatory geographical minimum tax when minimum tax applies.',
    ],
    commonMistakesBn: [
      'ডিপিএসে বছরে ১.২ লাখের বেশি জমা দিয়ে সম্পূর্ণ অর্থের ওপর রেয়াত আশা করা (ডিপিএস রেয়াত বছরে ১.২ লাখে সীমাবদ্ধ)।',
      'ন্যূনতম করের বাধ্যবাধকতা থাকা সত্ত্বেও রেয়াত দিয়ে কর শূন্য করার চেষ্টা করা।',
    ],
    officialSource: {
      title: 'Section 78, Income Tax Act 2023',
      actSection: 'Section 78 & Schedule 6 Part 3',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2023',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 6. Minimum Tax
  {
    slug: 'minimum-tax-rules-by-location',
    categoryId: 'minimum-tax',
    title: 'Geographical Minimum Tax Rules (Section 73)',
    titleBn: 'অঞ্চলভেদে ন্যূনতম করের বাধ্যবাধকতা (ধারা ৭৩)',
    shortExplanation: 'Mandatory minimum tax amounts depending on whether you live in Dhaka/Chattogram, other city corps, or rural areas.',
    shortExplanationBn: 'করযোগ্য আয় থাকলে ভৌগোলিক অবস্থানভেদে ন্যূনতম ৫,০০০, ৪,০০০ বা ৩,০০০ টাকা কর পরিশোধের বাধ্যবাধকতা।',
    whoItAppliesTo: 'Any individual taxpayer whose taxable income exceeds the tax-free limit.',
    whoItAppliesToBn: 'যেকোনো ব্যক্তি করদাতা যার করযোগ্য আয় করমুক্ত প্রারম্ভিক সীমা অতিক্রম করে।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'What is minimum tax and when do I have to pay ৳5,000, ৳4,000, or ৳3,000?',
    simpleQuestionBn: 'ন্যূনতম কর কী এবং কাদের ৫,০০০, ৪,০০০ বা ৩,০০০ টাকা দিতে হয়?',
    simpleAnswer:
      'If your taxable income exceeds the tax-free threshold (e.g. ৳3,50,000), the law requires you to pay a minimum fixed amount even if your calculated progressive tax after rebate is lower. The rates are: ৳5,000 in Dhaka/Chattogram, ৳4,000 in other City Corporations, and ৳3,000 in rural/non-city areas.',
    simpleAnswerBn:
      'আপনার করযোগ্য আয় করমুক্ত সীমা অতিক্রম করলে রেয়াত বা ছাড়ের পর কর যত কমই হোক না কেন, ভৌগোলিক অবস্থান অনুযায়ী নির্ধারিত ন্যূনতম কর পরিশোধ করতে হয়। ঢাকা ও চট্টগ্রামে ৫,০০০ টাকা, অন্যান্য সিটি কর্পোরেশনে ৪,০০০ টাকা এবং গ্রামীণ এলাকায় ৩,০০০ টাকা।',
    visualExample: {
      title: 'Example: Taxable Income ৳3,60,000 in Dhaka City Corporation',
      titleBn: 'বাস্তব উদাহরণ: ঢাকা সিটি কর্পোরেশনে ৩,৬০,০০০ টাকা আয় হলে',
      steps: [
        'Taxable Income: ৳3,60,000 (Exceeds ৳3,50,000 threshold)',
        'Progressive 5% tax on ৳10,000 = ৳500',
        'Dhaka Statutory Minimum Tax Requirement = ৳5,000',
        'Payable Tax = ৳5,000 (Raised to statutory minimum)',
      ],
      stepsBn: [
        'করযোগ্য আয়: ৩,৬০,০০০ টাকা (করমুক্ত ৩.৫ লাখের চেয়ে বেশি)',
        'অতিরিক্ত ১০,০০০ টাকার ওপর ৫% প্রগতিশীল কর = ৫০০ টাকা',
        'ঢাকা সিটি কর্পোরেশন বিধিবদ্ধ ন্যূনতম কর = ৫,০০০ টাকা',
        'প্রদেয় চূড়ান্ত কর = ৫,০০০ টাকা (ন্যূনতম কর প্রযোজ্য)',
      ],
      conclusion: 'If your income was ৳3,50,000 or below, your payable tax would be ৳0.',
      conclusionBn: 'আপনার আয় ৩,৫০,০০০ বা তার কম হলে প্রদেয় কর হতো ০ টাকা।',
    },
    commonMistakes: [
      'Thinking minimum tax applies when your total income is below the tax-free limit (it only triggers once income exceeds the threshold).',
      'Paying rural rate (৳3,00,0) when your principal source of employment or residence is in Dhaka or Chattogram.',
    ],
    commonMistakesBn: [
      'আয় করমুক্ত সীমার নিচে থাকলেও ন্যূনতম কর প্রযোজ্য হবে ভেবে ভুল করা।',
      'ঢাকা বা চট্টগ্রামে কর্মস্থল হওয়া সত্ত্বেও ভুলবশত পল্লী অঞ্চলের ৩,০০০ টাকা হারে কর জমা দেওয়া।',
    ],
    officialSource: {
      title: 'Section 73, Income Tax Act 2023',
      actSection: 'Section 73',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2023',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 7. Surcharge
  {
    slug: 'net-wealth-surcharge-explained',
    categoryId: 'surcharge',
    title: 'Net Wealth Surcharge Tiers & Specific Asset Triggers',
    titleBn: 'নিট সম্পদ সারচার্জ এবং একাধিক গাড়ির ক্ষেত্রে প্রযোজ্য নিয়মাবলী',
    shortExplanation: 'Additional surcharge levied on high net-worth individuals with assets above ৳4 Crore or multiple motor cars.',
    shortExplanationBn: '৪ কোটি টাকার বেশি নিট সম্পদের মালিক বা একাধিক মোটরগাড়ির ক্ষেত্রে আয়করের ওপর আরোপিত অতিরিক্ত সারচার্জ।',
    whoItAppliesTo: 'Taxpayers with net wealth exceeding ৳4 Crore or owners of multiple cars / 8,000+ sq ft property.',
    whoItAppliesToBn: '৪ কোটি টাকার বেশি সম্পদের মালিক, একাধিক গাড়ির মালিক অথবা ৮,০০০+ বর্গফুটের আবাসিক সম্পত্তির মালিকগণ।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'When does wealth surcharge apply and how is it calculated?',
    simpleQuestionBn: 'সারচার্জ কখন প্রযোজ্য হয় এবং এটি কীভাবে হিসাব করা হয়?',
    simpleAnswer:
      'Surcharge is an extra tax percentage calculated on top of your income tax liability (not on your total wealth). It starts at 10% if net wealth is between ৳4 Crore and ৳10 Crore, rising to 35% for wealth above ৳50 Crore. Owning 2 or more motor cars also triggers a 10% surcharge even if net wealth is below ৳4 Crore.',
    simpleAnswerBn:
      'সারচার্জ হলো মূল প্রদেয় আয়করের ওপর আরোপিত অতিরিক্ত শতকরা কর (সম্পদের মূল্যের ওপর সরাসরি নয়)। ৪ কোটি থেকে ১০ কোটি পর্যন্ত নিট সম্পদে ১০% এবং ৫০ কোটির উর্ধ্বে ৩৫% পর্যন্ত সারচার্জ প্রযোজ্য। এছাড়া একাধিক মোটরগাড়ির মালিক হলে সম্পদ ৪ কোটির কম হলেও ন্যূনতম ১০% সারচার্জ ধার্য হয়।',
    visualExample: {
      title: 'Example: Regular Tax ৳2,00,000 with Net Wealth of ৳5 Crore (10% Tier)',
      titleBn: 'বাস্তব উদাহরণ: প্রদেয় কর ২ লাখ এবং নিট সম্পদ ৫ কোটি টাকা হলে',
      steps: [
        'Income Tax Liability: ৳2,00,000',
        'Net Wealth: ৳5,00,000,00 (5 Crore → 10% Surcharge Tier)',
        'Surcharge Amount = 10% of ৳2,00,000 = ৳20,000',
        'Total Tax Payable = ৳2,00,000 + ৳20,000 = ৳2,20,000',
      ],
      stepsBn: [
        'মূল প্রদেয় কর: ২,০০,০০০ টাকা',
        'নিট সম্পদ: ৫,০০,০০,০০০ টাকা (৫ কোটি → ১০% সারচার্জ স্তর)',
        'সারচার্জের পরিমাণ = ২,০০,০০০ এর ১০% = ২০,০০০ টাকা',
        'মোট প্রদেয় কর = ২,০০,০০০ + ২০,০০০ = ২,২০,০০০ টাকা',
      ],
      conclusion: 'Surcharge is 10% of your tax bill, not 10% of your 5 Crore wealth.',
      conclusionBn: 'সারচার্জ হলো করের ওপর ১০%, পুরো ৫ কোটি টাকা সম্পদের ওপর ১০% নয়।',
    },
    commonMistakes: [
      'Assuming surcharge is deducted from your total asset balance rather than being a percentage of your annual tax bill.',
    ],
    commonMistakesBn: [
      'সম্পদের ওপর সরাসরি কর ধার্য হচ্ছে মনে করে সারচার্জের হিসাবে বিভ্রান্ত হওয়া।',
    ],
    officialSource: {
      title: 'Finance Act 2024 Surcharge Schedule',
      actSection: 'Finance Act 2024 Section 4',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2024',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 8. Tax Return
  {
    slug: 'who-must-file-tax-return-bangladesh',
    categoryId: 'tax-return',
    title: 'Who is Legally Required to File a Tax Return?',
    titleBn: 'আইনানুসারে কাদের জন্য আয়কর রিটার্ন দাখিল করা বাধ্যতামূলক?',
    shortExplanation: 'Mandatory return submission conditions under Section 166 of the Income Tax Act 2023.',
    shortExplanationBn: 'আয়কর আইন ২০২৩-এর ১৬৬ ও ২৬৪ ধারা অনুযায়ী বাধ্যতামূলক রিটার্ন দাখিলের আওতাভুক্ত খাতসমূহ।',
    whoItAppliesTo: 'Anyone holding a TIN with income above the threshold or engaged in 43+ statutory economic activities.',
    whoItAppliesToBn: 'করযোগ্য আয়ের অধিকারী অথবা নির্দিষ্ট ৪৩+ সরকারি ও বাণিজ্যিক সেবা গ্রহণকারী টিআইএনধারী নাগরিক।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'Do I have to file a tax return if my income is zero or below the threshold?',
    simpleQuestionBn: 'আয় করমুক্ত সীমার নিচে বা শূন্য হলেও কি রিটার্ন দাখিল করতে হবে?',
    simpleAnswer:
      'Under the Income Tax Act 2023, submitting proof of return submission (PSR) is mandatory for 43+ services—including taking bank loans above ৳5 Lakh, obtaining trade licenses, buying motor cars, and maintaining credit cards. If you hold a TIN and use these services, you must file a return even if your calculated tax is ৳0.',
    simpleAnswerBn:
      'আয়কর আইন ২০২৩ অনুসারে ৫ লাখ টাকার বেশি ব্যাংক ঋণ, ট্রেড লাইসেন্স, ক্রেডিট কার্ড ও গাড়ি রেজিস্ট্রেশনসহ ৪৩+ সেবার জন্য রিটার্ন দাখিলের প্রমাণপত্র (PSR) বাধ্যতামূলক। আপনি যদি এসব সেবা গ্রহণ করেন, তবে কর শূন্য হলেও আপনাকে রিটার্ন জমা দিতে হবে।',
    visualExample: {
      title: 'Mandatory Return Submission Triggers',
      titleBn: 'রিটার্ন দাখিল বাধ্যতামূলক হওয়ার প্রধান ক্ষেত্রসমূহ',
      steps: [
        'Obtaining or renewing a Trade License',
        'Applying for a credit card or bank loan above ৳5,00,000',
        'Purchasing or registering a motor vehicle',
        'Being an executive employee in a company or NGO',
        'Participating in government tenders or e-GP',
      ],
      stepsBn: [
        'ট্রেড লাইসেন্স গ্রহণ বা নবায়ন',
        'ক্রেডিট কার্ড বা ৫ লাখ টাকার বেশি ব্যাংক ঋণ আবেদন',
        'মোটরযান ক্রয় বা রেজিস্ট্রেশন',
        'কোম্পানি বা এনজিওর নির্বাহী পদে চাকরি',
        'সরকারি টেন্ডার বা ই-জিপিতে অংশগ্রহণ',
      ],
      conclusion: 'Filing a return with ৳0 tax is legal and fulfills your statutory compliance.',
      conclusionBn: 'প্রদেয় কর শূন্য (০) দেখিয়ে রিটার্ন দাখিল করা সম্পূর্ণ আইনসম্মত ও বাধ্যতামূলক।',
    },
    commonMistakes: [
      'Ignoring return filing because you had ৳0 tax, resulting in bank account freezes or service blocks.',
      'Missing the 30 November Tax Day deadline and facing late filing interest fees.',
    ],
    commonMistakesBn: [
      'কর শূন্য হওয়ায় রিটার্ন দাখিল না করে পরবর্তীতে ব্যাংক অ্যাকাউন্ট বা সেবায় জটিলতায় পড়া।',
      '৩০ নভেম্বরের কর দিবসের মধ্যে রিটার্ন দাখিল না করে বিলম্ব মাশুল বা জরিমানার মুখোমুখি হওয়া।',
    ],
    officialSource: {
      title: 'Section 166, Income Tax Act 2023',
      actSection: 'Section 166 & Section 264',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2023',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },

  // 9. e-Return
  {
    slug: 'how-to-file-online-ereturn-nbr',
    categoryId: 'e-return',
    title: 'How to File Your Tax Return Online (e-Return)',
    titleBn: 'অনলাইনে এনবিআর ই-রিটার্ন দাখিল করার সহজ নিয়ম',
    shortExplanation: 'Step-by-step guide on registering and filing your return on the official NBR e-Return portal (etaxnbr.gov.bd).',
    shortExplanationBn: 'জাতীয় রাজস্ব বোর্ডের অফিশিয়াল পোর্টাল (etaxnbr.gov.bd) এ ঘরে বসেই পেপারলেস রিটার্ন জমার নিয়ম।',
    whoItAppliesTo: 'All individual taxpayers filing annual returns digitally.',
    whoItAppliesToBn: 'অনলাইনে কাগজবিহীন রিটার্ন দাখিল করতে ইচ্ছুক সকল ব্যক্তি করদাতা।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'How do I submit my return online without visiting a tax office?',
    simpleQuestionBn: 'কর অফিসে না গিয়ে কীভাবে অনলাইনে ঘরে বসে রিটার্ন জমা দেওয়া যায়?',
    simpleAnswer:
      'The National Board of Revenue operates the official portal at etaxnbr.gov.bd. You register using your 12-digit e-TIN and biometric SIM registered with your NID. You fill in your income, allowances, and investments, review the draft, and submit online to receive an instant acknowledgment receipt and tax certificate.',
    simpleAnswerBn:
      'জাতীয় রাজস্ব বোর্ডের অফিশিয়াল পোর্টাল etaxnbr.gov.bd এ আপনার ১২ সংখ্যার ই-টিআইএন এবং জাতীয় পরিচয়পত্রে বায়োমেট্রিক রেজিস্ট্রিকৃত সিম দিয়ে নিবন্ধন করুন। এরপর আয়ের তথ্য, কর ছাড় ও বিনিয়োগ পূরণ করে জমা দিন এবং সাথে সাথে স্বীকৃতিপত্র ও কর সনদ ডাউনলোড করুন।',
    visualExample: {
      title: '4 Steps to e-Return Submission',
      titleBn: 'ই-রিটার্ন দাখিলের ৪টি সহজ ধাপ',
      steps: [
        'Step 1: Sign up at etaxnbr.gov.bd with e-TIN and biometric SIM',
        'Step 2: Enter income sources, deductions, and Section 78 investments',
        'Step 3: Review the auto-generated Form IT-11GA draft',
        'Step 4: Submit electronically and download your instant Tax Certificate',
      ],
      stepsBn: [
        'ধাপ ১: etaxnbr.gov.bd এ গিয়ে ই-টিআইএন ও বায়োমেট্রিক সিম দিয়ে সাইন আপ করুন',
        'ধাপ ২: বেতন ও অন্যান্য আয়ের বিবরণ, কর ছাড় এবং ধারা ৭৮ এর বিনিয়োগ যোগ করুন',
        'ধাপ ৩: স্বয়ংক্রিয়ভাবে প্রস্তুতকৃত আইটি-১১গ ড্রাফট রিটার্ন ফর্মটি যাচাই করুন',
        'ধাপ ৪: অনলাইনে সাবমিট করে সাথে সাথে প্রাপ্তি স্বীকারপত্র ও ট্যাক্স সার্টিফিকেট ডাউনলোড করুন',
      ],
      conclusion: 'No physical paper submission or tax office queue required.',
      conclusionBn: 'কোনো কাগুজে ফাইল জমা বা কর অফিসে লাইনে দাঁড়ানোর প্রয়োজন নেই।',
    },
    commonMistakes: [
      'Registering with a SIM card not biometric-linked to your own NID (OTP will fail).',
      'Forgetting to download and save the official Acknowledgment Receipt after submission.',
    ],
    commonMistakesBn: [
      'নিজের এনআইডিতে নিবন্ধিত নয় এমন সিম দিয়ে চেষ্টা করা (ওটিপি আসবে না)।',
      'সাবমিট করার পর অফিশিয়াল প্রাপ্তি স্বীকারপত্র ও সার্টিফিকেট সংরক্ষণ করতে ভুলে যাওয়া।',
    ],
    officialSource: {
      title: 'NBR Official e-Return Portal Guidance',
      actSection: 'Section 174, Income Tax Act 2023',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'July 2024',
      lastVerified: 'September 2024',
      sourceUrl: 'https://etaxnbr.gov.bd',
    },
  },

  // 10. Taxpayer Categories
  {
    slug: 'taxpayer-categories-and-exemption-thresholds',
    categoryId: 'taxpayer-categories',
    title: 'Taxpayer Categories & Special Tax-Free Thresholds',
    titleBn: 'করদাতার বিভিন্ন শ্রেণি ও বিশেষ করমুক্ত সীমার বিবরণ',
    shortExplanation: 'Special statutory exemption limits for women, senior citizens, third gender, disabled individuals, and freedom fighters.',
    shortExplanationBn: 'নারী, ৬৫+ প্রবীণ, তৃতীয় লিঙ্গ, প্রতিবন্ধী ব্যক্তি ও গেজেটভুক্ত মুক্তিযোদ্ধাদের জন্য প্রযোজ্য বিশেষ করমুক্ত সীমা।',
    whoItAppliesTo: 'Female taxpayers, citizens aged 65+, third gender community, disabled individuals, and freedom fighters.',
    whoItAppliesToBn: 'নারী করদাতা, ৬৫+ বয়সের প্রবীণ নাগরিক, তৃতীয় লিঙ্গ, প্রতিবন্ধী এবং গেজেটভুক্ত যুদ্ধাহত মুক্তিযোদ্ধাগণ।',
    assessmentYear: '2024-2025',
    lastVerified: 'September 2024',
    simpleQuestion: 'How much tax-free income is allowed for different categories of taxpayers?',
    simpleQuestionBn: 'বিভিন্ন শ্রেণির করদাতাদের জন্য করমুক্ত আয়ের সীমা কত টাকা?',
    simpleAnswer:
      'To provide equity and social support, Bangladesh law provides higher tax-free thresholds for specific groups. While general male taxpayers have a ৳3,50,000 threshold, women and senior citizens (65+) get ৳4,00,000, disabled persons get ৳4,75,000, and gazetted freedom fighters get ৳5,00,000.',
    simpleAnswerBn:
      'সামাজিক সমতা ও সুরক্ষার স্বার্থে আইনে বিভিন্ন শ্রেণির করদাতার জন্য বর্ধিত করমুক্ত সীমা রাখা হয়েছে। সাধারণ পুরুষ করদাতাদের জন্য ৩.৫০ লাখ টাকা, নারী ও ৬৫+ প্রবীণদের জন্য ৪.০০ লাখ টাকা, প্রতিবন্ধী ব্যক্তিদের জন্য ৪.৭৫ লাখ টাকা এবং মুক্তিযোদ্ধাদের জন্য ৫.০০ লাখ টাকা পর্যন্ত আয় সম্পূর্ণ করমুক্ত।',
    visualExample: {
      title: 'Summary of Statutory Thresholds (AY 2024-2025)',
      titleBn: 'করবর্ষ ২০২৪-২০২৫ এর সংবিধিবদ্ধ করমুক্ত সীমা সারসংক্ষেপ',
      steps: [
        'General Male Taxpayers: ৳3,50,000 Tax-Free',
        'Female Taxpayers: ৳4,00,000 Tax-Free',
        'Senior Citizens (65+ years): ৳4,00,000 Tax-Free',
        'Third Gender Taxpayers: ৳4,00,000 Tax-Free',
        'Physically Challenged / Disabled: ৳4,75,000 Tax-Free',
        'Gazetted War-Wounded Freedom Fighters: ৳5,00,000 Tax-Free',
        'Parents of Disabled Children: Extra +৳50,000 per child',
      ],
      stepsBn: [
        'সাধারণ পুরুষ করদাতা: ৩,৫০,০০০ টাকা করমুক্ত',
        'নারী করদাতা: ৪,০০,০০০ টাকা করমুক্ত',
        'প্রবীণ নাগরিক (৬৫+ বছর): ৪,০০,০০০ টাকা করমুক্ত',
        'তৃতীয় লিঙ্গের করদাতা: ৪,০০,০০০ টাকা করমুক্ত',
        'প্রতিবন্ধী ব্যক্তি করদাতা: ৪,৭৫,০০০ টাকা করমুক্ত',
        'গেজেটভুক্ত যুদ্ধাহত মুক্তিযোদ্ধা: ৫,০০,০০০ টাকা করমুক্ত',
        'প্রতিবন্ধী সন্তানের অভিভাবক: প্রতি সন্তানের জন্য অতিরিক্ত +৫০,০০০ টাকা',
      ],
      conclusion: 'Your category is automatically factored into your progressive calculation.',
      conclusionBn: 'আপনার করদাতা শ্রেণি অনুযায়ী স্বয়ংক্রিয়ভাবে প্রগতিশীল কর ধাপ নির্ধারিত হবে।',
    },
    commonMistakes: [
      'Senior citizens aged 65+ calculating under the general ৳3.5L threshold instead of claiming the ৳4.0L senior allowance.',
      'Parents of disabled children missing the additional ৳50,000 per child exemption.',
    ],
    commonMistakesBn: [
      '৬৫+ বয়সের করদাতারা ভুলবশত সাধারণ ৩.৫ লাখ সীমার বদলে ৪.০ লাখের সুবিধা দাবি করতে ভুলে যাওয়া।',
      'প্রতিবন্ধী সন্তানের পিতা-মাতার জন্য সন্তান প্রতি অতিরিক্ত ৫০,০০০ টাকার ছাড় যুক্ত না করা।',
    ],
    officialSource: {
      title: 'Finance Act 2024 & Paripatra 2024-2025',
      actSection: 'First Schedule / NBR Paripatra',
      authority: 'National Board of Revenue (NBR)',
      publicationDate: 'June 2024',
      lastVerified: 'September 2024',
      sourceUrl: 'https://nbr.gov.bd',
    },
  },
];

export const TAX_GLOSSARY = [
  {
    term: 'Taxable Income',
    bangla: 'করযোগ্য আয়',
    definition: 'The net portion of your total annual earnings that is subjected to income tax slabs after subtracting all statutory deductions, exemptions, and allowances.',
    definitionBn: 'মোট বার্ষিক উপার্জন থেকে সংবিধিবদ্ধ করমুক্ত অংশ ও ভাতা বাদ দেওয়ার পর যে অবশিষ্ট আয়ের ওপর কর ধার্য হয়।',
    example: 'If your salary is ৳10,00,000 and you have ৳3,00,000 in allowable exemptions, your Taxable Income is ৳7,00,000.',
    exampleBn: 'মোট বেতন ১০ লাখ এবং অনুমোদনযোগ্য করমুক্ত ভাতা ৩ লাখ হলে আপনার করযোগ্য আয় হবে ৭ লাখ টাকা।',
    source: 'Section 32, Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
  },
  {
    term: 'Assessment Year (AY)',
    bangla: 'করবর্ষ',
    definition: 'The 12-month period starting on 1 July and ending on 30 June during which the tax on income earned in the preceding Income Year is assessed and collected.',
    definitionBn: '১ জুলাই থেকে ৩০ জুন পর্যন্ত ১২ মাসের সময়কাল, যে সময়ে পূর্ববর্তী আয়বর্ষের উপার্জিত আয়ের ওপর কর নির্ধারণ ও দাখিল করা হয়।',
    example: 'For income earned between 1 July 2023 and 30 June 2024, the Assessment Year is 2024–2025.',
    exampleBn: '১ জুলাই ২০২৩ থেকে ৩০ জুন ২০২৪ এর আয়ের জন্য করবর্ষ হলো ২০২৪–২০২৫।',
    source: 'Section 2(9), Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
  },
  {
    term: 'Income Year',
    bangla: 'আয়বর্ষ',
    definition: 'The financial year (1 July to 30 June) during which income is actually earned by the taxpayer prior to assessment.',
    definitionBn: 'যে নির্দিষ্ট অর্থবছরে করদাতা প্রকৃত অর্থ উপার্জন করেছেন (১ জুলাই থেকে ৩০ জুন)।',
    example: 'Income earned from 1 July 2023 to 30 June 2024 belongs to Income Year 2023–2024.',
    exampleBn: '১ জুলাই ২০২৩ থেকে ৩০ জুন ২০২৪ পর্যন্ত উপার্জিত আয় হলো আয়বর্ষ ২০২৩–২০২৪ এর অন্তর্ভুক্ত।',
    source: 'Section 2(10), Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
  },
  {
    term: 'Tax Rebate',
    bangla: 'কর রেয়াত',
    definition: 'A direct deduction subtracted from calculated gross income tax liability earned through approved investments under Section 78.',
    definitionBn: 'ধারা ৭৮ অনুযায়ী অনুমোদিত খাতে বিনিয়োগের মাধ্যমে প্রাথমিক করদায় থেকে সরাসরি কর্তনযোগ্য কর ছাড়।',
    example: 'If your regular tax is ৳40,000 and your Section 78 rebate is ৳15,000, you only pay ৳25,000.',
    exampleBn: 'প্রাথমিক কর ৪০,০০০ টাকা এবং ধারা ৭৮ রেয়াত ১৫,০০০ টাকা হলে আপনাকে নিট ২৫,০০০ টাকা কর দিতে হবে।',
    source: 'Section 78, Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
  },
  {
    term: 'Surcharge',
    bangla: 'সারচার্জ',
    definition: 'An additional wealth-based tax percentage levied on high net-worth individuals whose total net assets exceed ৳4 Crore or who own multiple motor vehicles.',
    definitionBn: '৪ কোটি টাকার বেশি নিট সম্পদের অধিকারী বা একাধিক গাড়ির মালিকদের মূল প্রদেয় করের ওপর ধার্যকৃত অতিরিক্ত কর।',
    example: 'A taxpayer with ৳5 Crore net wealth pays a 10% surcharge on their calculated tax bill.',
    exampleBn: '৫ কোটি টাকার সম্পদের অধিকারী করদাতা তার প্রদেয় করের ওপর ১০% হারে সারচার্জ পরিশোধ করবেন।',
    source: 'Finance Act 2024, Section 4',
    authority: 'National Board of Revenue (NBR)',
  },
  {
    term: 'Withholding Tax (TDS / AIT)',
    bangla: 'উৎস কর / অগ্রিম আয়কর',
    definition: 'Tax deducted at source in advance by employers, banks, or paying authorities prior to transferring payment to the taxpayer.',
    definitionBn: 'বেতন, ব্যাংক মুনাফা বা বাণিজ্যিক বিল পরিশোধের সময় উৎস কর্তনকারী কর্তৃপক্ষ কর্তৃক অগ্রিম কর্তিত কর।',
    example: 'Banks automatically deduct 10% or 15% TDS on interest earned from Fixed Deposits (FDR).',
    exampleBn: 'এফডিআর বা ব্যাংক আমানতের মুনাফা দেওয়ার সময় ব্যাংক স্বয়ংক্রিয়ভাবে ১০% বা ১৫% উৎস কর কর্তন করে।',
    source: 'Chapter 7, Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
  },
  {
    term: 'Tax Return (Form IT-11GA)',
    bangla: 'আয়কর রিটার্ন',
    definition: 'The official annual statutory declaration detailing a taxpayer’s income, assets, liabilities, and tax calculations submitted to the NBR.',
    definitionBn: 'করদাতার বার্ষিক আয়, ব্যয়, সম্পদ, দায় ও কর গণনার সংবিধিবদ্ধ বার্ষিক বিবরণী ফর্ম।',
    example: 'Submitted online via etaxnbr.gov.bd or physically to the relevant tax circle by 30 November.',
    exampleBn: 'অনলাইনে etaxnbr.gov.bd অথবা সংশ্লিষ্ট কর সার্কেলে ৩০ নভেম্বরের মধ্যে জমা দেওয়া হয়।',
    source: 'Section 166, Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
  },
  {
    term: 'e-TIN (Taxpayer Identification Number)',
    bangla: 'ই-টিন নম্বর',
    definition: 'A unique 12-digit digital identification number issued by the NBR to track and maintain a taxpayer’s official record.',
    definitionBn: 'জাতীয় রাজস্ব বোর্ড কর্তৃক করদাতার পরিচিতি শনাক্তকরণে প্রদত্ত ১২ সংখ্যার ডিজিটাল নম্বর।',
    example: 'Required to open merchant accounts, apply for credit cards, or register commercial properties.',
    exampleBn: 'ব্যাংক অ্যাকাউন্ট, ক্রেডিট কার্ড, ট্রেড লাইসেন্স ও জমি রেজিস্ট্রেশনে প্রয়োজন হয়।',
    source: 'Section 261, Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
  },
  {
    term: 'e-Return Portal',
    bangla: 'অনলাইন রিটার্ন পোর্টাল',
    definition: 'The official digital web platform provided by the National Board of Revenue (etaxnbr.gov.bd) for paperless return submission and certificate download.',
    definitionBn: 'জাতীয় রাজস্ব বোর্ডের অফিশিয়াল ডিজিটাল পোর্টাল (etaxnbr.gov.bd), যার মাধ্যমে ঘরে বসেই অনলাইন রিটার্ন দাখিল ও কর সনদ পাওয়া যায়।',
    example: 'Allows taxpayers to file returns, calculate tax, pay via mobile banking/cards, and download proof of submission instantly.',
    exampleBn: 'এর মাধ্যমে করদাতা অনলাইনে কর হিসাব, বিকাশ/কার্ডে পেমেন্ট এবং সাথে সাথে প্রাপ্তি স্বীকারপত্র ডাউনলোড করতে পারেন।',
    source: 'Section 174, Income Tax Act 2023',
    authority: 'National Board of Revenue (NBR)',
  },
];
